/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getFuncionarioResponseDtoSchema } from './getFuncionarioResponseDtoSchema.ts';
import { z } from 'zod/v4';

export const funcionariosControllerFindAll200Schema = z.array(
  getFuncionarioResponseDtoSchema
);

export const funcionariosControllerFindAllQueryResponseSchema =
  funcionariosControllerFindAll200Schema;
