/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const funcionariosControllerFindAll200Schema = z.any();

export const funcionariosControllerFindAllQueryResponseSchema =
  funcionariosControllerFindAll200Schema;
