/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { funcionarioDtoSchema } from './funcionarioDtoSchema.ts';
import { z } from 'zod/v4';

export const getFuncionarioResponseDtoSchema = z.object({
  get funcionario() {
    return funcionarioDtoSchema;
  },
});
