/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const healthControllerGetHealth200Schema = z.any();

export const healthControllerGetHealthQueryResponseSchema =
  healthControllerGetHealth200Schema;
