/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const updateFuncionarioDtoSchema = z.object({
  nome: z.optional(z.string().min(1).max(100)),
  social: z.optional(z.string().min(0).max(100)),
  cpf: z.optional(z.string().min(1).max(15)),
  nascimento: z.optional(z.string()),
  phone: z.optional(z.string().min(0).max(20)),
  email: z.optional(z.email()),
  rg: z.optional(z.string().min(0).max(11)),
});
