/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  AuthControllerLogoutMutationRequest,
  AuthControllerLogoutMutationResponse,
} from '../../types/AuthControllerLogout';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const authControllerLogoutMutationKey = () =>
  [{ url: '/auth/logout' }] as const;

export type AuthControllerLogoutMutationKey = ReturnType<
  typeof authControllerLogoutMutationKey
>;

/**
 * {@link /auth/logout}
 */
export async function authControllerLogout(
  data?: AuthControllerLogoutMutationRequest,
  config: Partial<RequestConfig<AuthControllerLogoutMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AuthControllerLogoutMutationResponse,
    ResponseErrorConfig<Error>,
    AuthControllerLogoutMutationRequest
  >({
    method: 'POST',
    url: `/auth/logout`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function authControllerLogoutMutationOptions(
  config: Partial<RequestConfig<AuthControllerLogoutMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = authControllerLogoutMutationKey();
  return mutationOptions<
    AuthControllerLogoutMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerLogoutMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return authControllerLogout(data, config);
    },
  });
}

/**
 * {@link /auth/logout}
 */
export function useAuthControllerLogout<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AuthControllerLogoutMutationResponse,
      ResponseErrorConfig<Error>,
      { data?: AuthControllerLogoutMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AuthControllerLogoutMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? authControllerLogoutMutationKey();

  const baseOptions = authControllerLogoutMutationOptions(
    config
  ) as UseMutationOptions<
    AuthControllerLogoutMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerLogoutMutationRequest },
    TContext
  >;

  return useMutation<
    AuthControllerLogoutMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerLogoutMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AuthControllerLogoutMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: AuthControllerLogoutMutationRequest },
    TContext
  >;
}
