/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AuthResponseDto = {
  /**
   * @type string, email
   */
  accessToken: string;
  /**
   * @type string
   */
  refreshToken: string;
};
