/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthResponseDto } from './AuthResponseDto';
import type { RefreshDto } from './RefreshDto';

export type AuthControllerRefresh201 = AuthResponseDto;

export type AuthControllerRefreshMutationRequest = RefreshDto;

export type AuthControllerRefreshMutationResponse = AuthControllerRefresh201;

export type AuthControllerRefreshMutation = {
  Response: AuthControllerRefresh201;
  Request: AuthControllerRefreshMutationRequest;
  Errors: any;
};
