/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RefreshDto } from './RefreshDto.ts';

export type AuthControllerRefresh201 = any;

export type AuthControllerRefreshMutationRequest = RefreshDto;

export type AuthControllerRefreshMutationResponse = AuthControllerRefresh201;

export type AuthControllerRefreshMutation = {
  Response: AuthControllerRefresh201;
  Request: AuthControllerRefreshMutationRequest;
  Errors: any;
};
