/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginDto } from './LoginDto.ts';

export type AuthControllerLogin201 = any;

export type AuthControllerLoginMutationRequest = LoginDto;

export type AuthControllerLoginMutationResponse = AuthControllerLogin201;

export type AuthControllerLoginMutation = {
  Response: AuthControllerLogin201;
  Request: AuthControllerLoginMutationRequest;
  Errors: any;
};
