/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateLookupDto = {
  /**
   * @type string
   */
  grupo: string;
  /**
   * @type string
   */
  nome: string;
};
