/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateFuncionarioDto = {
  /**
   * @minLength 1
   * @maxLength 100
   * @type string | undefined
   */
  nome?: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @type string | undefined
   */
  social?: string;
  /**
   * @minLength 1
   * @maxLength 15
   * @type string
   */
  cpf: string;
  /**
   * @type string | undefined
   */
  nascimento?: string;
  /**
   * @minLength 0
   * @maxLength 20
   * @type string | undefined
   */
  phone?: string;
  /**
   * @type string, email
   */
  email: string;
  /**
   * @type string
   */
  projetoId: string;
  /**
   * @minLength 0
   * @maxLength 11
   * @type string | undefined
   */
  rg?: string;
  /**
   * @minLength 0
   * @maxLength 30
   * @type string
   */
  funcao: string;
  /**
   * @type number
   */
  dependetes: number;
  /**
   * @type number | undefined
   */
  valorCafe?: number;
  /**
   * @type number | undefined
   */
  valorSaudeOcupacional?: number;
  /**
   * @type number | undefined
   */
  valorSaudePlano?: number;
  /**
   * @type number | undefined
   */
  valorJanta?: number;
  /**
   * @type number | undefined
   */
  valorDescontoCasa?: number;
};
