/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateDiariaDto } from './CreateDiariaDto';

export type CreateManyDiariasDto = {
  /**
   * @type array
   */
  items: CreateDiariaDto[];
};
