/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateDiariaDto = {
  /**
   * @type string
   */
  projetoId: string;
  /**
   * @type string
   */
  funcionarioId: string;
  /**
   * @type string
   */
  dia: string;
};
