/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProjetoDto = {
  /**
   * @type string | undefined
   */
  empresaId?: string;
  /**
   * @minLength 1
   * @maxLength 100
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  inicio: string;
  /**
   * @type string
   */
  fim: string;
};
