/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateEmpresaDto = {
  /**
   * @minLength 1
   * @maxLength 100
   * @type string | undefined
   */
  razao?: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @type string | undefined
   */
  fantasia?: string;
  /**
   * @minLength 1
   * @maxLength 15
   * @type string
   */
  cnpj: string;
  /**
   * @type string | undefined
   */
  registro?: string;
  /**
   * @minLength 0
   * @maxLength 20
   * @type string | undefined
   */
  phone?: string;
  /**
   * @type string, email
   */
  email: string;
};
