/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DiariaDto } from './DiariaDto.ts';

export type DiariasControllerFindInRangeQueryParams = {
  /**
   * @type string
   */
  from: string;
  /**
   * @type string
   */
  to: string;
};

export type DiariasControllerFindInRange200 = DiariaDto[];

export type DiariasControllerFindInRangeQueryResponse =
  DiariasControllerFindInRange200;

export type DiariasControllerFindInRangeQuery = {
  Response: DiariasControllerFindInRange200;
  QueryParams: DiariasControllerFindInRangeQueryParams;
  Errors: any;
};
