/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DiariaDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  dia: string;
  /**
   * @type string
   */
  funcionarioId: string;
  /**
   * @type string
   */
  projetoId: string;
  /**
   * @type string
   */
  tipoDiaria: string;
  /**
   * @type string
   */
  observacoes: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
};
