/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateDiariaDto } from './CreateDiariaDto.ts';
import type { DiariaDto } from './DiariaDto.ts';

export type DiariasControllerUpdatePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type DiariasControllerUpdate200 = DiariaDto;

export type DiariasControllerUpdateMutationRequest = CreateDiariaDto;

export type DiariasControllerUpdateMutationResponse =
  DiariasControllerUpdate200;

export type DiariasControllerUpdateMutation = {
  Response: DiariasControllerUpdate200;
  Request: DiariasControllerUpdateMutationRequest;
  PathParams: DiariasControllerUpdatePathParams;
  Errors: any;
};
