/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateDiariaDto } from './UpdateDiariaDto.ts';

export type DiariasControllerUpdateDiaria200 = any;

export type DiariasControllerUpdateDiariaMutationRequest = UpdateDiariaDto;

export type DiariasControllerUpdateDiariaMutationResponse =
  DiariasControllerUpdateDiaria200;

export type DiariasControllerUpdateDiariaMutation = {
  Response: DiariasControllerUpdateDiaria200;
  Request: DiariasControllerUpdateDiariaMutationRequest;
  Errors: any;
};
