/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateManyDiariasDto } from './CreateManyDiariasDto';
import type { DiariaDto } from './DiariaDto';

export type DiariasControllerCreateMany201 = DiariaDto[];

export type DiariasControllerCreateManyMutationRequest = CreateManyDiariasDto;

export type DiariasControllerCreateManyMutationResponse =
  DiariasControllerCreateMany201;

export type DiariasControllerCreateManyMutation = {
  Response: DiariasControllerCreateMany201;
  Request: DiariasControllerCreateManyMutationRequest;
  Errors: any;
};
