/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateDiariaDto } from './CreateDiariaDto.ts';
import type { DiariaEntity } from './DiariaEntity.ts';

export type DiariasControllerCreate201 = DiariaEntity;

export type DiariasControllerCreateMutationRequest = CreateDiariaDto;

export type DiariasControllerCreateMutationResponse =
  DiariasControllerCreate201;

export type DiariasControllerCreateMutation = {
  Response: DiariasControllerCreate201;
  Request: DiariasControllerCreateMutationRequest;
  Errors: any;
};
