/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateDiariaDto } from './CreateDiariaDto';
import type { DiariaDto } from './DiariaDto';

export type DiariasControllerCreate201 = DiariaDto;

export type DiariasControllerCreateMutationRequest = CreateDiariaDto;

export type DiariasControllerCreateMutationResponse =
  DiariasControllerCreate201;

export type DiariasControllerCreateMutation = {
  Response: DiariasControllerCreate201;
  Request: DiariasControllerCreateMutationRequest;
  Errors: any;
};
