/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateEmpresaDto } from './CreateEmpresaDto.ts';

export type EmpresasControllerCreate201 = object;

export type EmpresasControllerCreateMutationRequest = CreateEmpresaDto;

export type EmpresasControllerCreateMutationResponse =
  EmpresasControllerCreate201;

export type EmpresasControllerCreateMutation = {
  Response: EmpresasControllerCreate201;
  Request: EmpresasControllerCreateMutationRequest;
  Errors: any;
};
