/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EmpresaDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  razao: string;
  /**
   * @type string
   */
  fantasia: string;
  /**
   * @type string
   */
  cnpj: string;
  /**
   * @type string
   */
  registro: string;
  /**
   * @type string
   */
  phone: string;
  /**
   * @type string
   */
  email: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
};
