/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EmpresasControllerRemovePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type EmpresasControllerRemove200 = any;

export type EmpresasControllerRemoveMutationResponse =
  EmpresasControllerRemove200;

export type EmpresasControllerRemoveMutation = {
  Response: EmpresasControllerRemove200;
  PathParams: EmpresasControllerRemovePathParams;
  Errors: any;
};
