/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EmpresaDto } from './EmpresaDto.ts';

export type EmpresasControllerFindAll200 = EmpresaDto[];

export type EmpresasControllerFindAllQueryResponse =
  EmpresasControllerFindAll200;

export type EmpresasControllerFindAllQuery = {
  Response: EmpresasControllerFindAll200;
  Errors: any;
};
