/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetEmpresaResponseDto } from './GetEmpresaResponseDto.ts';

export type EmpresasControllerFindOnePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type EmpresasControllerFindOne200 = GetEmpresaResponseDto;

export type EmpresasControllerFindOneQueryResponse =
  EmpresasControllerFindOne200;

export type EmpresasControllerFindOneQuery = {
  Response: EmpresasControllerFindOne200;
  PathParams: EmpresasControllerFindOnePathParams;
  Errors: any;
};
