/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateEmpresaDto } from './UpdateEmpresaDto';

export type EmpresasControllerUpdatePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type EmpresasControllerUpdate200 = object;

export type EmpresasControllerUpdateMutationRequest = UpdateEmpresaDto;

export type EmpresasControllerUpdateMutationResponse =
  EmpresasControllerUpdate200;

export type EmpresasControllerUpdateMutation = {
  Response: EmpresasControllerUpdate200;
  Request: EmpresasControllerUpdateMutationRequest;
  PathParams: EmpresasControllerUpdatePathParams;
  Errors: any;
};
