/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FuncionarioDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  social: string;
  /**
   * @type string
   */
  cpf: string;
  /**
   * @type string
   */
  nascimento: string;
  /**
   * @type string
   */
  phone: string;
  /**
   * @type string
   */
  email: string;
  /**
   * @type string
   */
  rg: string;
  /**
   * @type string
   */
  funcao: string;
  /**
   * @type number
   */
  salario: number;
  /**
   * @type number
   */
  dependetes: number;
  /**
   * @type string
   */
  projetoId: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
  /**
   * @type number
   */
  decimoTerceiro: number;
  /**
   * @type number
   */
  ferias: number;
};
