/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FuncionariosControllerFindAll200 = any;

export type FuncionariosControllerFindAllQueryResponse =
  FuncionariosControllerFindAll200;

export type FuncionariosControllerFindAllQuery = {
  Response: FuncionariosControllerFindAll200;
  Errors: any;
};
