/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateFuncionarioDto } from './CreateFuncionarioDto';

export type FuncionariosControllerCreate201 = object;

export type FuncionariosControllerCreateMutationRequest = CreateFuncionarioDto;

export type FuncionariosControllerCreateMutationResponse =
  FuncionariosControllerCreate201;

export type FuncionariosControllerCreateMutation = {
  Response: FuncionariosControllerCreate201;
  Request: FuncionariosControllerCreateMutationRequest;
  Errors: any;
};
