/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FuncionarioDto } from './FuncionarioDto';

export type FuncionariosControllerFindAll200 = FuncionarioDto[];

export type FuncionariosControllerFindAllQueryResponse =
  FuncionariosControllerFindAll200;

export type FuncionariosControllerFindAllQuery = {
  Response: FuncionariosControllerFindAll200;
  Errors: any;
};
