/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FuncionarioBeneficioDto = {
  /**
   * @type string
   */
  lookupId: string;
  /**
   * @type number
   */
  valor: number;
};
