/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateFuncionarioDto } from './UpdateFuncionarioDto';

export type FuncionariosControllerUpdatePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type FuncionariosControllerUpdate200 = object;

export type FuncionariosControllerUpdateMutationRequest = UpdateFuncionarioDto;

export type FuncionariosControllerUpdateMutationResponse =
  FuncionariosControllerUpdate200;

export type FuncionariosControllerUpdateMutation = {
  Response: FuncionariosControllerUpdate200;
  Request: FuncionariosControllerUpdateMutationRequest;
  PathParams: FuncionariosControllerUpdatePathParams;
  Errors: any;
};
