/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FuncionariosControllerRemovePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type FuncionariosControllerRemove200 = any;

export type FuncionariosControllerRemoveMutationResponse =
  FuncionariosControllerRemove200;

export type FuncionariosControllerRemoveMutation = {
  Response: FuncionariosControllerRemove200;
  PathParams: FuncionariosControllerRemovePathParams;
  Errors: any;
};
