/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetFuncionarioResponseDto } from './GetFuncionarioResponseDto';

export type FuncionariosControllerFindOnePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type FuncionariosControllerFindOne200 = GetFuncionarioResponseDto;

export type FuncionariosControllerFindOneQueryResponse =
  FuncionariosControllerFindOne200;

export type FuncionariosControllerFindOneQuery = {
  Response: FuncionariosControllerFindOne200;
  PathParams: FuncionariosControllerFindOnePathParams;
  Errors: any;
};
