/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EmpresaDto } from './EmpresaDto.ts';

export type GetEmpresaResponseDto = {
  /**
   * @type object
   */
  empresa: EmpresaDto;
};
