/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FuncionarioDto } from './FuncionarioDto';

export type GetFuncionarioResponseDto = {
  /**
   * @type object
   */
  funcionario: FuncionarioDto;
};
