/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LookupDto } from './LookupDto';

export type LookupsControllerFindByGroupPathParams = {
  /**
   * @type string
   */
  grupo: string;
};

export type LookupsControllerFindByGroup200 = LookupDto[];

export type LookupsControllerFindByGroupQueryResponse =
  LookupsControllerFindByGroup200;

export type LookupsControllerFindByGroupQuery = {
  Response: LookupsControllerFindByGroup200;
  PathParams: LookupsControllerFindByGroupPathParams;
  Errors: any;
};
