/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LookupsControllerRemovePathParams = {
  /**
   * @type string
   */
  grupo: string;
  /**
   * @type string
   */
  id: string;
};

export type LookupsControllerRemove200 = any;

export type LookupsControllerRemoveMutationResponse =
  LookupsControllerRemove200;

export type LookupsControllerRemoveMutation = {
  Response: LookupsControllerRemove200;
  PathParams: LookupsControllerRemovePathParams;
  Errors: any;
};
