/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LookupDto } from './LookupDto.ts';

export type LookupsControllerFindAll200 = LookupDto[];

export type LookupsControllerFindAllQueryResponse = LookupsControllerFindAll200;

export type LookupsControllerFindAllQuery = {
  Response: LookupsControllerFindAll200;
  Errors: any;
};
