/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LookupDto = {
  /**
   * @type string
   */
  grupo: string;
  /**
   * @type number
   */
  key: number;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string;
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string;
};
