/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LookupsControllerFindOnePathParams = {
  /**
   * @type string
   */
  grupo: string;
  /**
   * @type string
   */
  id: string;
};

export type LookupsControllerFindOne200 = any;

export type LookupsControllerFindOneQueryResponse = LookupsControllerFindOne200;

export type LookupsControllerFindOneQuery = {
  Response: LookupsControllerFindOne200;
  PathParams: LookupsControllerFindOnePathParams;
  Errors: any;
};
