/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateLookupDto } from './CreateLookupDto';

export type LookupsControllerCreate201 = any;

export type LookupsControllerCreateMutationRequest = CreateLookupDto;

export type LookupsControllerCreateMutationResponse =
  LookupsControllerCreate201;

export type LookupsControllerCreateMutation = {
  Response: LookupsControllerCreate201;
  Request: LookupsControllerCreateMutationRequest;
  Errors: any;
};
