/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateLookupDto } from './UpdateLookupDto.ts';

export type LookupsControllerUpdatePathParams = {
  /**
   * @type string
   */
  grupo: string;
  /**
   * @type number
   */
  key: number;
};

export type LookupsControllerUpdate200 = any;

export type LookupsControllerUpdateMutationRequest = UpdateLookupDto;

export type LookupsControllerUpdateMutationResponse =
  LookupsControllerUpdate200;

export type LookupsControllerUpdateMutation = {
  Response: LookupsControllerUpdate200;
  Request: LookupsControllerUpdateMutationRequest;
  PathParams: LookupsControllerUpdatePathParams;
  Errors: any;
};
