/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProjetosControllerFindAll200 = object[];

export type ProjetosControllerFindAllQueryResponse =
  ProjetosControllerFindAll200;

export type ProjetosControllerFindAllQuery = {
  Response: ProjetosControllerFindAll200;
  Errors: any;
};
