/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProjetosControllerRemovePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type ProjetosControllerRemove200 = any;

export type ProjetosControllerRemoveMutationResponse =
  ProjetosControllerRemove200;

export type ProjetosControllerRemoveMutation = {
  Response: ProjetosControllerRemove200;
  PathParams: ProjetosControllerRemovePathParams;
  Errors: any;
};
