/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjetoDto } from './ProjetoDto';

export type ProjetosControllerFindAll200 = ProjetoDto[];

export type ProjetosControllerFindAllQueryResponse =
  ProjetosControllerFindAll200;

export type ProjetosControllerFindAllQuery = {
  Response: ProjetosControllerFindAll200;
  Errors: any;
};
