/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjetoDto } from './ProjetoDto';

export type ProjetosControllerFindOnePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type ProjetosControllerFindOne200 = ProjetoDto;

export type ProjetosControllerFindOneQueryResponse =
  ProjetosControllerFindOne200;

export type ProjetosControllerFindOneQuery = {
  Response: ProjetosControllerFindOne200;
  PathParams: ProjetosControllerFindOnePathParams;
  Errors: any;
};
