/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateProjetoDto } from './UpdateProjetoDto';

export type ProjetosControllerUpdatePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type ProjetosControllerUpdate200 = object;

export type ProjetosControllerUpdateMutationRequest = UpdateProjetoDto;

export type ProjetosControllerUpdateMutationResponse =
  ProjetosControllerUpdate200;

export type ProjetosControllerUpdateMutation = {
  Response: ProjetosControllerUpdate200;
  Request: ProjetosControllerUpdateMutationRequest;
  PathParams: ProjetosControllerUpdatePathParams;
  Errors: any;
};
