/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProjetoDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  empresaId: string;
  /**
   * @type string
   */
  nome: string;
  /**
   * @type string
   */
  inicio: string;
  /**
   * @type string
   */
  fim: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
};
