/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateProjetoDto } from './CreateProjetoDto.ts';

export type ProjetosControllerCreate201 = object;

export type ProjetosControllerCreateMutationRequest = CreateProjetoDto;

export type ProjetosControllerCreateMutationResponse =
  ProjetosControllerCreate201;

export type ProjetosControllerCreateMutation = {
  Response: ProjetosControllerCreate201;
  Request: ProjetosControllerCreateMutationRequest;
  Errors: any;
};
