/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TiposDiariaControllerFindAll200 = any;

export type TiposDiariaControllerFindAllQueryResponse =
  TiposDiariaControllerFindAll200;

export type TiposDiariaControllerFindAllQuery = {
  Response: TiposDiariaControllerFindAll200;
  Errors: any;
};
