/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TipoDiariaDto } from './TipoDiariaDto';

export type TiposDiariaControllerFindAll200 = TipoDiariaDto[];

export type TiposDiariaControllerFindAllQueryResponse =
  TiposDiariaControllerFindAll200;

export type TiposDiariaControllerFindAllQuery = {
  Response: TiposDiariaControllerFindAll200;
  Errors: any;
};
