/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateDiariaDto = {
  /**
   * @type string
   */
  funcionarioId: string;
  /**
   * @type string
   */
  projetoId: string;
  /**
   * @type string
   */
  dia: string;
  /**
   * @type object
   */
  tipo: object;
};
