/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateProjetoDto = {
  /**
   * @type string | undefined
   */
  empresaId?: string;
  /**
   * @minLength 1
   * @maxLength 100
   * @type string | undefined
   */
  nome?: string;
  /**
   * @type string | undefined
   */
  inicio?: string;
  /**
   * @type string | undefined
   */
  fim?: string;
};
