/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateLookupDto = {
  /**
   * @type string | undefined
   */
  grupo?: string;
  /**
   * @type string | undefined
   */
  key?: string;
  /**
   * @type string | undefined
   */
  nome?: string;
};
