/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateEmpresaDto = {
  /**
   * @minLength 1
   * @maxLength 100
   * @type string | undefined
   */
  razao?: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @type string | undefined
   */
  fantasia?: string;
  /**
   * @minLength 1
   * @maxLength 15
   * @type string | undefined
   */
  cnpj?: string;
  /**
   * @type string | undefined
   */
  registro?: string;
  /**
   * @minLength 0
   * @maxLength 20
   * @type string | undefined
   */
  phone?: string;
  /**
   * @type string | undefined, email
   */
  email?: string;
};
