/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateFuncionarioDto = {
  /**
   * @minLength 1
   * @maxLength 100
   * @type string | undefined
   */
  nome?: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @type string | undefined
   */
  social?: string;
  /**
   * @minLength 1
   * @maxLength 15
   * @type string | undefined
   */
  cpf?: string;
  /**
   * @type string | undefined
   */
  nascimento?: string;
  /**
   * @minLength 0
   * @maxLength 20
   * @type string | undefined
   */
  phone?: string;
  /**
   * @type string | undefined, email
   */
  email?: string;
  /**
   * @type string | undefined
   */
  projetoId?: string;
  /**
   * @minLength 0
   * @maxLength 11
   * @type string | undefined
   */
  rg?: string;
  /**
   * @minLength 0
   * @maxLength 30
   * @type string | undefined
   */
  funcao?: string;
  /**
   * @type number | undefined
   */
  dependetes?: number;
};
