/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type { TiposDiariaControllerFindAllQueryResponse } from '../../types';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const tiposDiariaControllerFindAllQueryKey = () =>
  [{ url: '/tipos-diarias' }] as const;

export type TiposDiariaControllerFindAllQueryKey = ReturnType<
  typeof tiposDiariaControllerFindAllQueryKey
>;

/**
 * {@link /tipos-diarias}
 */
export async function tiposDiariaControllerFindAll(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    TiposDiariaControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/tipos-diarias`, ...requestConfig });
  return res.data;
}

export function tiposDiariaControllerFindAllQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = tiposDiariaControllerFindAllQueryKey();
  return queryOptions<
    TiposDiariaControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    TiposDiariaControllerFindAllQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return tiposDiariaControllerFindAll(config);
    },
  });
}

/**
 * {@link /tipos-diarias}
 */
export function useTiposDiariaControllerFindAll<
  TData = TiposDiariaControllerFindAllQueryResponse,
  TQueryData = TiposDiariaControllerFindAllQueryResponse,
  TQueryKey extends QueryKey = TiposDiariaControllerFindAllQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        TiposDiariaControllerFindAllQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? tiposDiariaControllerFindAllQueryKey();

  const query = useQuery(
    {
      ...tiposDiariaControllerFindAllQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
