/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type { FuncionariosControllerFindAllQueryResponse } from '../../types/FuncionariosControllerFindAll';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const funcionariosControllerFindAllQueryKey = () =>
  [{ url: '/funcionarios' }] as const;

export type FuncionariosControllerFindAllQueryKey = ReturnType<
  typeof funcionariosControllerFindAllQueryKey
>;

/**
 * {@link /funcionarios}
 */
export async function funcionariosControllerFindAll(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FuncionariosControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/funcionarios`, ...requestConfig });
  return res.data;
}

export function funcionariosControllerFindAllQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = funcionariosControllerFindAllQueryKey();
  return queryOptions<
    FuncionariosControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    FuncionariosControllerFindAllQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return funcionariosControllerFindAll(config);
    },
  });
}

/**
 * {@link /funcionarios}
 */
export function useFuncionariosControllerFindAll<
  TData = FuncionariosControllerFindAllQueryResponse,
  TQueryData = FuncionariosControllerFindAllQueryResponse,
  TQueryKey extends QueryKey = FuncionariosControllerFindAllQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        FuncionariosControllerFindAllQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? funcionariosControllerFindAllQueryKey();

  const query = useQuery(
    {
      ...funcionariosControllerFindAllQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
