/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  FuncionariosControllerRemoveMutationResponse,
  FuncionariosControllerRemovePathParams,
} from '../../types/FuncionariosControllerRemove.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const funcionariosControllerRemoveMutationKey = () =>
  [{ url: '/funcionarios/:id' }] as const;

export type FuncionariosControllerRemoveMutationKey = ReturnType<
  typeof funcionariosControllerRemoveMutationKey
>;

/**
 * {@link /funcionarios/:id}
 */
export async function funcionariosControllerRemove(
  id: FuncionariosControllerRemovePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FuncionariosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'DELETE', url: `/funcionarios/${id}`, ...requestConfig });
  return res.data;
}

export function funcionariosControllerRemoveMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const mutationKey = funcionariosControllerRemoveMutationKey();
  return mutationOptions<
    FuncionariosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: FuncionariosControllerRemovePathParams['id'] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return funcionariosControllerRemove(id, config);
    },
  });
}

/**
 * {@link /funcionarios/:id}
 */
export function useFuncionariosControllerRemove<TContext>(
  options: {
    mutation?: UseMutationOptions<
      FuncionariosControllerRemoveMutationResponse,
      ResponseErrorConfig<Error>,
      { id: FuncionariosControllerRemovePathParams['id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? funcionariosControllerRemoveMutationKey();

  const baseOptions = funcionariosControllerRemoveMutationOptions(
    config
  ) as UseMutationOptions<
    FuncionariosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: FuncionariosControllerRemovePathParams['id'] },
    TContext
  >;

  return useMutation<
    FuncionariosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: FuncionariosControllerRemovePathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    FuncionariosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: FuncionariosControllerRemovePathParams['id'] },
    TContext
  >;
}
