/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  FuncionariosControllerCreateMutationRequest,
  FuncionariosControllerCreateMutationResponse,
} from '../../types/FuncionariosControllerCreate';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const funcionariosControllerCreateMutationKey = () =>
  [{ url: '/funcionarios' }] as const;

export type FuncionariosControllerCreateMutationKey = ReturnType<
  typeof funcionariosControllerCreateMutationKey
>;

/**
 * {@link /funcionarios}
 */
export async function funcionariosControllerCreate(
  data: FuncionariosControllerCreateMutationRequest,
  config: Partial<
    RequestConfig<FuncionariosControllerCreateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FuncionariosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    FuncionariosControllerCreateMutationRequest
  >({
    method: 'POST',
    url: `/funcionarios`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function funcionariosControllerCreateMutationOptions(
  config: Partial<
    RequestConfig<FuncionariosControllerCreateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const mutationKey = funcionariosControllerCreateMutationKey();
  return mutationOptions<
    FuncionariosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: FuncionariosControllerCreateMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return funcionariosControllerCreate(data, config);
    },
  });
}

/**
 * {@link /funcionarios}
 */
export function useFuncionariosControllerCreate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      FuncionariosControllerCreateMutationResponse,
      ResponseErrorConfig<Error>,
      { data: FuncionariosControllerCreateMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<FuncionariosControllerCreateMutationRequest>
    > & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? funcionariosControllerCreateMutationKey();

  const baseOptions = funcionariosControllerCreateMutationOptions(
    config
  ) as UseMutationOptions<
    FuncionariosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: FuncionariosControllerCreateMutationRequest },
    TContext
  >;

  return useMutation<
    FuncionariosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: FuncionariosControllerCreateMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    FuncionariosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: FuncionariosControllerCreateMutationRequest },
    TContext
  >;
}
