/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  FuncionariosControllerUpdateMutationRequest,
  FuncionariosControllerUpdateMutationResponse,
  FuncionariosControllerUpdatePathParams,
} from '../../types/FuncionariosControllerUpdate';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const funcionariosControllerUpdateMutationKey = () =>
  [{ url: '/funcionarios/:id' }] as const;

export type FuncionariosControllerUpdateMutationKey = ReturnType<
  typeof funcionariosControllerUpdateMutationKey
>;

/**
 * {@link /funcionarios/:id}
 */
export async function funcionariosControllerUpdate(
  id: FuncionariosControllerUpdatePathParams['id'],
  data?: FuncionariosControllerUpdateMutationRequest,
  config: Partial<
    RequestConfig<FuncionariosControllerUpdateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    FuncionariosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    FuncionariosControllerUpdateMutationRequest
  >({
    method: 'PATCH',
    url: `/funcionarios/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function funcionariosControllerUpdateMutationOptions(
  config: Partial<
    RequestConfig<FuncionariosControllerUpdateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const mutationKey = funcionariosControllerUpdateMutationKey();
  return mutationOptions<
    FuncionariosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: FuncionariosControllerUpdatePathParams['id'];
      data?: FuncionariosControllerUpdateMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return funcionariosControllerUpdate(id, data, config);
    },
  });
}

/**
 * {@link /funcionarios/:id}
 */
export function useFuncionariosControllerUpdate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      FuncionariosControllerUpdateMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: FuncionariosControllerUpdatePathParams['id'];
        data?: FuncionariosControllerUpdateMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<FuncionariosControllerUpdateMutationRequest>
    > & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? funcionariosControllerUpdateMutationKey();

  const baseOptions = funcionariosControllerUpdateMutationOptions(
    config
  ) as UseMutationOptions<
    FuncionariosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: FuncionariosControllerUpdatePathParams['id'];
      data?: FuncionariosControllerUpdateMutationRequest;
    },
    TContext
  >;

  return useMutation<
    FuncionariosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: FuncionariosControllerUpdatePathParams['id'];
      data?: FuncionariosControllerUpdateMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    FuncionariosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: FuncionariosControllerUpdatePathParams['id'];
      data?: FuncionariosControllerUpdateMutationRequest;
    },
    TContext
  >;
}
