/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  FuncionariosControllerFindOneQueryResponse,
  FuncionariosControllerFindOnePathParams,
} from '../../types/FuncionariosControllerFindOne';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const funcionariosControllerFindOneQueryKey = (
  id: FuncionariosControllerFindOnePathParams['id']
) => [{ url: '/funcionarios/:id', params: { id: id } }] as const;

export type FuncionariosControllerFindOneQueryKey = ReturnType<
  typeof funcionariosControllerFindOneQueryKey
>;

/**
 * {@link /funcionarios/:id}
 */
export async function funcionariosControllerFindOne(
  id: FuncionariosControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    FuncionariosControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/funcionarios/${id}`, ...requestConfig });
  return res.data;
}

export function funcionariosControllerFindOneQueryOptions(
  id: FuncionariosControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = funcionariosControllerFindOneQueryKey(id);
  return queryOptions<
    FuncionariosControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    FuncionariosControllerFindOneQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return funcionariosControllerFindOne(id, config);
    },
  });
}

/**
 * {@link /funcionarios/:id}
 */
export function useFuncionariosControllerFindOne<
  TData = FuncionariosControllerFindOneQueryResponse,
  TQueryData = FuncionariosControllerFindOneQueryResponse,
  TQueryKey extends QueryKey = FuncionariosControllerFindOneQueryKey
>(
  id: FuncionariosControllerFindOnePathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        FuncionariosControllerFindOneQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? funcionariosControllerFindOneQueryKey(id);

  const query = useQuery(
    {
      ...funcionariosControllerFindOneQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
