/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  EmpresasControllerUpdateMutationRequest,
  EmpresasControllerUpdateMutationResponse,
  EmpresasControllerUpdatePathParams,
} from '../../types/EmpresasControllerUpdate';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const empresasControllerUpdateMutationKey = () =>
  [{ url: '/empresas/:id' }] as const;

export type EmpresasControllerUpdateMutationKey = ReturnType<
  typeof empresasControllerUpdateMutationKey
>;

/**
 * {@link /empresas/:id}
 */
export async function empresasControllerUpdate(
  id: EmpresasControllerUpdatePathParams['id'],
  data?: EmpresasControllerUpdateMutationRequest,
  config: Partial<RequestConfig<EmpresasControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    EmpresasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    EmpresasControllerUpdateMutationRequest
  >({
    method: 'PATCH',
    url: `/empresas/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function empresasControllerUpdateMutationOptions(
  config: Partial<RequestConfig<EmpresasControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = empresasControllerUpdateMutationKey();
  return mutationOptions<
    EmpresasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: EmpresasControllerUpdatePathParams['id'];
      data?: EmpresasControllerUpdateMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return empresasControllerUpdate(id, data, config);
    },
  });
}

/**
 * {@link /empresas/:id}
 */
export function useEmpresasControllerUpdate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      EmpresasControllerUpdateMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: EmpresasControllerUpdatePathParams['id'];
        data?: EmpresasControllerUpdateMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<EmpresasControllerUpdateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? empresasControllerUpdateMutationKey();

  const baseOptions = empresasControllerUpdateMutationOptions(
    config
  ) as UseMutationOptions<
    EmpresasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: EmpresasControllerUpdatePathParams['id'];
      data?: EmpresasControllerUpdateMutationRequest;
    },
    TContext
  >;

  return useMutation<
    EmpresasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: EmpresasControllerUpdatePathParams['id'];
      data?: EmpresasControllerUpdateMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    EmpresasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: EmpresasControllerUpdatePathParams['id'];
      data?: EmpresasControllerUpdateMutationRequest;
    },
    TContext
  >;
}
