/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  EmpresasControllerFindOneQueryResponse,
  EmpresasControllerFindOnePathParams,
} from '../../types/EmpresasControllerFindOne';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const empresasControllerFindOneQueryKey = (
  id: EmpresasControllerFindOnePathParams['id']
) => [{ url: '/empresas/:id', params: { id: id } }] as const;

export type EmpresasControllerFindOneQueryKey = ReturnType<
  typeof empresasControllerFindOneQueryKey
>;

/**
 * {@link /empresas/:id}
 */
export async function empresasControllerFindOne(
  id: EmpresasControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EmpresasControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/empresas/${id}`, ...requestConfig });
  return res.data;
}

export function empresasControllerFindOneQueryOptions(
  id: EmpresasControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = empresasControllerFindOneQueryKey(id);
  return queryOptions<
    EmpresasControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    EmpresasControllerFindOneQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return empresasControllerFindOne(id, config);
    },
  });
}

/**
 * {@link /empresas/:id}
 */
export function useEmpresasControllerFindOne<
  TData = EmpresasControllerFindOneQueryResponse,
  TQueryData = EmpresasControllerFindOneQueryResponse,
  TQueryKey extends QueryKey = EmpresasControllerFindOneQueryKey
>(
  id: EmpresasControllerFindOnePathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        EmpresasControllerFindOneQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? empresasControllerFindOneQueryKey(id);

  const query = useQuery(
    {
      ...empresasControllerFindOneQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
