/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  EmpresasControllerCreateMutationRequest,
  EmpresasControllerCreateMutationResponse,
} from '../../types/EmpresasControllerCreate';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const empresasControllerCreateMutationKey = () =>
  [{ url: '/empresas' }] as const;

export type EmpresasControllerCreateMutationKey = ReturnType<
  typeof empresasControllerCreateMutationKey
>;

/**
 * {@link /empresas}
 */
export async function empresasControllerCreate(
  data: EmpresasControllerCreateMutationRequest,
  config: Partial<RequestConfig<EmpresasControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    EmpresasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    EmpresasControllerCreateMutationRequest
  >({ method: 'POST', url: `/empresas`, data: requestData, ...requestConfig });
  return res.data;
}

export function empresasControllerCreateMutationOptions(
  config: Partial<RequestConfig<EmpresasControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = empresasControllerCreateMutationKey();
  return mutationOptions<
    EmpresasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: EmpresasControllerCreateMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return empresasControllerCreate(data, config);
    },
  });
}

/**
 * {@link /empresas}
 */
export function useEmpresasControllerCreate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      EmpresasControllerCreateMutationResponse,
      ResponseErrorConfig<Error>,
      { data: EmpresasControllerCreateMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<EmpresasControllerCreateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? empresasControllerCreateMutationKey();

  const baseOptions = empresasControllerCreateMutationOptions(
    config
  ) as UseMutationOptions<
    EmpresasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: EmpresasControllerCreateMutationRequest },
    TContext
  >;

  return useMutation<
    EmpresasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: EmpresasControllerCreateMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    EmpresasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: EmpresasControllerCreateMutationRequest },
    TContext
  >;
}
