/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type { EmpresasControllerFindAllQueryResponse } from '../../types/EmpresasControllerFindAll';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const empresasControllerFindAllQueryKey = () =>
  [{ url: '/empresas' }] as const;

export type EmpresasControllerFindAllQueryKey = ReturnType<
  typeof empresasControllerFindAllQueryKey
>;

/**
 * {@link /empresas}
 */
export async function empresasControllerFindAll(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EmpresasControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/empresas`, ...requestConfig });
  return res.data;
}

export function empresasControllerFindAllQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = empresasControllerFindAllQueryKey();
  return queryOptions<
    EmpresasControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    EmpresasControllerFindAllQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return empresasControllerFindAll(config);
    },
  });
}

/**
 * {@link /empresas}
 */
export function useEmpresasControllerFindAll<
  TData = EmpresasControllerFindAllQueryResponse,
  TQueryData = EmpresasControllerFindAllQueryResponse,
  TQueryKey extends QueryKey = EmpresasControllerFindAllQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        EmpresasControllerFindAllQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? empresasControllerFindAllQueryKey();

  const query = useQuery(
    {
      ...empresasControllerFindAllQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
