/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  EmpresasControllerRemoveMutationResponse,
  EmpresasControllerRemovePathParams,
} from '../../types/EmpresasControllerRemove';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const empresasControllerRemoveMutationKey = () =>
  [{ url: '/empresas/:id' }] as const;

export type EmpresasControllerRemoveMutationKey = ReturnType<
  typeof empresasControllerRemoveMutationKey
>;

/**
 * {@link /empresas/:id}
 */
export async function empresasControllerRemove(
  id: EmpresasControllerRemovePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    EmpresasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'DELETE', url: `/empresas/${id}`, ...requestConfig });
  return res.data;
}

export function empresasControllerRemoveMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const mutationKey = empresasControllerRemoveMutationKey();
  return mutationOptions<
    EmpresasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: EmpresasControllerRemovePathParams['id'] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return empresasControllerRemove(id, config);
    },
  });
}

/**
 * {@link /empresas/:id}
 */
export function useEmpresasControllerRemove<TContext>(
  options: {
    mutation?: UseMutationOptions<
      EmpresasControllerRemoveMutationResponse,
      ResponseErrorConfig<Error>,
      { id: EmpresasControllerRemovePathParams['id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? empresasControllerRemoveMutationKey();

  const baseOptions = empresasControllerRemoveMutationOptions(
    config
  ) as UseMutationOptions<
    EmpresasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: EmpresasControllerRemovePathParams['id'] },
    TContext
  >;

  return useMutation<
    EmpresasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: EmpresasControllerRemovePathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    EmpresasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: EmpresasControllerRemovePathParams['id'] },
    TContext
  >;
}
