/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client';
import type { RequestConfig, ResponseErrorConfig } from '../../client';
import type {
  PessoasJuridicasControllerFindAllQueryResponse,
  PessoasJuridicasControllerFindAllQueryParams,
} from '../types/PessoasJuridicasControllerFindAll.ts';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const pessoasJuridicasControllerFindAllQueryKey = (
  params: PessoasJuridicasControllerFindAllQueryParams
) => [{ url: '/pessoas-juridicas' }, ...(params ? [params] : [])] as const;

export type PessoasJuridicasControllerFindAllQueryKey = ReturnType<
  typeof pessoasJuridicasControllerFindAllQueryKey
>;

/**
 * {@link /pessoas-juridicas}
 */
export async function pessoasJuridicasControllerFindAll(
  params: PessoasJuridicasControllerFindAllQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PessoasJuridicasControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/pessoas-juridicas`, params, ...requestConfig });
  return res.data;
}

export function pessoasJuridicasControllerFindAllQueryOptions(
  params: PessoasJuridicasControllerFindAllQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = pessoasJuridicasControllerFindAllQueryKey(params);
  return queryOptions<
    PessoasJuridicasControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    PessoasJuridicasControllerFindAllQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return pessoasJuridicasControllerFindAll(params, config);
    },
  });
}

/**
 * {@link /pessoas-juridicas}
 */
export function usePessoasJuridicasControllerFindAll<
  TData = PessoasJuridicasControllerFindAllQueryResponse,
  TQueryData = PessoasJuridicasControllerFindAllQueryResponse,
  TQueryKey extends QueryKey = PessoasJuridicasControllerFindAllQueryKey
>(
  params: PessoasJuridicasControllerFindAllQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        PessoasJuridicasControllerFindAllQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? pessoasJuridicasControllerFindAllQueryKey(params);

  const query = useQuery(
    {
      ...pessoasJuridicasControllerFindAllQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
