/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client';
import type { RequestConfig, ResponseErrorConfig } from '../../client';
import type {
  PessoasJuridicasControllerFindOneQueryResponse,
  PessoasJuridicasControllerFindOnePathParams,
  PessoasJuridicasControllerFindOneQueryParams,
} from '../types/PessoasJuridicasControllerFindOne.ts';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const pessoasJuridicasControllerFindOneQueryKey = (
  id: PessoasJuridicasControllerFindOnePathParams['id'],
  params: PessoasJuridicasControllerFindOneQueryParams
) =>
  [
    { url: '/pessoas-juridicas/:id', params: { id: id } },
    ...(params ? [params] : []),
  ] as const;

export type PessoasJuridicasControllerFindOneQueryKey = ReturnType<
  typeof pessoasJuridicasControllerFindOneQueryKey
>;

/**
 * {@link /pessoas-juridicas/:id}
 */
export async function pessoasJuridicasControllerFindOne(
  id: PessoasJuridicasControllerFindOnePathParams['id'],
  params: PessoasJuridicasControllerFindOneQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PessoasJuridicasControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: `/pessoas-juridicas/${id}`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function pessoasJuridicasControllerFindOneQueryOptions(
  id: PessoasJuridicasControllerFindOnePathParams['id'],
  params: PessoasJuridicasControllerFindOneQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = pessoasJuridicasControllerFindOneQueryKey(id, params);
  return queryOptions<
    PessoasJuridicasControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    PessoasJuridicasControllerFindOneQueryResponse,
    typeof queryKey
  >({
    enabled: !!(id && params),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return pessoasJuridicasControllerFindOne(id, params, config);
    },
  });
}

/**
 * {@link /pessoas-juridicas/:id}
 */
export function usePessoasJuridicasControllerFindOne<
  TData = PessoasJuridicasControllerFindOneQueryResponse,
  TQueryData = PessoasJuridicasControllerFindOneQueryResponse,
  TQueryKey extends QueryKey = PessoasJuridicasControllerFindOneQueryKey
>(
  id: PessoasJuridicasControllerFindOnePathParams['id'],
  params: PessoasJuridicasControllerFindOneQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        PessoasJuridicasControllerFindOneQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    pessoasJuridicasControllerFindOneQueryKey(id, params);

  const query = useQuery(
    {
      ...pessoasJuridicasControllerFindOneQueryOptions(id, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
