/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client';
import type { RequestConfig, ResponseErrorConfig } from '../../client';
import type {
  PessoasJuridicasControllerRemoveMutationResponse,
  PessoasJuridicasControllerRemovePathParams,
  PessoasJuridicasControllerRemoveQueryParams,
} from '../types/PessoasJuridicasControllerRemove.ts';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const pessoasJuridicasControllerRemoveMutationKey = () =>
  [{ url: '/pessoas-juridicas/:id' }] as const;

export type PessoasJuridicasControllerRemoveMutationKey = ReturnType<
  typeof pessoasJuridicasControllerRemoveMutationKey
>;

/**
 * {@link /pessoas-juridicas/:id}
 */
export async function pessoasJuridicasControllerRemove(
  id: PessoasJuridicasControllerRemovePathParams['id'],
  params: PessoasJuridicasControllerRemoveQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PessoasJuridicasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'DELETE',
    url: `/pessoas-juridicas/${id}`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function pessoasJuridicasControllerRemoveMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const mutationKey = pessoasJuridicasControllerRemoveMutationKey();
  return mutationOptions<
    PessoasJuridicasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerRemovePathParams['id'];
      params: PessoasJuridicasControllerRemoveQueryParams;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, params }) => {
      return pessoasJuridicasControllerRemove(id, params, config);
    },
  });
}

/**
 * {@link /pessoas-juridicas/:id}
 */
export function usePessoasJuridicasControllerRemove<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PessoasJuridicasControllerRemoveMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: PessoasJuridicasControllerRemovePathParams['id'];
        params: PessoasJuridicasControllerRemoveQueryParams;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    pessoasJuridicasControllerRemoveMutationKey();

  const baseOptions = pessoasJuridicasControllerRemoveMutationOptions(
    config
  ) as UseMutationOptions<
    PessoasJuridicasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerRemovePathParams['id'];
      params: PessoasJuridicasControllerRemoveQueryParams;
    },
    TContext
  >;

  return useMutation<
    PessoasJuridicasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerRemovePathParams['id'];
      params: PessoasJuridicasControllerRemoveQueryParams;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PessoasJuridicasControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerRemovePathParams['id'];
      params: PessoasJuridicasControllerRemoveQueryParams;
    },
    TContext
  >;
}
