/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client';
import type { RequestConfig, ResponseErrorConfig } from '../../client';
import type {
  PessoasJuridicasControllerCreateMutationRequest,
  PessoasJuridicasControllerCreateMutationResponse,
} from '../types/PessoasJuridicasControllerCreate.ts';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const pessoasJuridicasControllerCreateMutationKey = () =>
  [{ url: '/pessoas-juridicas' }] as const;

export type PessoasJuridicasControllerCreateMutationKey = ReturnType<
  typeof pessoasJuridicasControllerCreateMutationKey
>;

/**
 * {@link /pessoas-juridicas}
 */
export async function pessoasJuridicasControllerCreate(
  data: PessoasJuridicasControllerCreateMutationRequest,
  config: Partial<
    RequestConfig<PessoasJuridicasControllerCreateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PessoasJuridicasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    PessoasJuridicasControllerCreateMutationRequest
  >({
    method: 'POST',
    url: `/pessoas-juridicas`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function pessoasJuridicasControllerCreateMutationOptions(
  config: Partial<
    RequestConfig<PessoasJuridicasControllerCreateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const mutationKey = pessoasJuridicasControllerCreateMutationKey();
  return mutationOptions<
    PessoasJuridicasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PessoasJuridicasControllerCreateMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return pessoasJuridicasControllerCreate(data, config);
    },
  });
}

/**
 * {@link /pessoas-juridicas}
 */
export function usePessoasJuridicasControllerCreate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PessoasJuridicasControllerCreateMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PessoasJuridicasControllerCreateMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PessoasJuridicasControllerCreateMutationRequest>
    > & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    pessoasJuridicasControllerCreateMutationKey();

  const baseOptions = pessoasJuridicasControllerCreateMutationOptions(
    config
  ) as UseMutationOptions<
    PessoasJuridicasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PessoasJuridicasControllerCreateMutationRequest },
    TContext
  >;

  return useMutation<
    PessoasJuridicasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PessoasJuridicasControllerCreateMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PessoasJuridicasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PessoasJuridicasControllerCreateMutationRequest },
    TContext
  >;
}
