/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '../../client';
import type { RequestConfig, ResponseErrorConfig } from '../../client';
import type {
  PessoasJuridicasControllerUpdateMutationRequest,
  PessoasJuridicasControllerUpdateMutationResponse,
  PessoasJuridicasControllerUpdatePathParams,
} from '../types/PessoasJuridicasControllerUpdate.ts';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const pessoasJuridicasControllerUpdateMutationKey = () =>
  [{ url: '/pessoas-juridicas/:id' }] as const;

export type PessoasJuridicasControllerUpdateMutationKey = ReturnType<
  typeof pessoasJuridicasControllerUpdateMutationKey
>;

/**
 * {@link /pessoas-juridicas/:id}
 */
export async function pessoasJuridicasControllerUpdate(
  id: PessoasJuridicasControllerUpdatePathParams['id'],
  data?: PessoasJuridicasControllerUpdateMutationRequest,
  config: Partial<
    RequestConfig<PessoasJuridicasControllerUpdateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PessoasJuridicasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    PessoasJuridicasControllerUpdateMutationRequest
  >({
    method: 'PATCH',
    url: `/pessoas-juridicas/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function pessoasJuridicasControllerUpdateMutationOptions(
  config: Partial<
    RequestConfig<PessoasJuridicasControllerUpdateMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const mutationKey = pessoasJuridicasControllerUpdateMutationKey();
  return mutationOptions<
    PessoasJuridicasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerUpdatePathParams['id'];
      data?: PessoasJuridicasControllerUpdateMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return pessoasJuridicasControllerUpdate(id, data, config);
    },
  });
}

/**
 * {@link /pessoas-juridicas/:id}
 */
export function usePessoasJuridicasControllerUpdate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PessoasJuridicasControllerUpdateMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: PessoasJuridicasControllerUpdatePathParams['id'];
        data?: PessoasJuridicasControllerUpdateMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PessoasJuridicasControllerUpdateMutationRequest>
    > & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    pessoasJuridicasControllerUpdateMutationKey();

  const baseOptions = pessoasJuridicasControllerUpdateMutationOptions(
    config
  ) as UseMutationOptions<
    PessoasJuridicasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerUpdatePathParams['id'];
      data?: PessoasJuridicasControllerUpdateMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PessoasJuridicasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerUpdatePathParams['id'];
      data?: PessoasJuridicasControllerUpdateMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PessoasJuridicasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PessoasJuridicasControllerUpdatePathParams['id'];
      data?: PessoasJuridicasControllerUpdateMutationRequest;
    },
    TContext
  >;
}
