import { IsOptional, IsString } from 'class-validator';

export class CreateLookupDto {
  @IsString()
  grupo!: string;

  // `key` is generated by DB, do not provide on create
  @IsOptional()
  @IsString()
  key?: string;

  @IsString()
  nome!: string;
}
