/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { loginDtoSchema } from './loginDtoSchema.ts';
import { z } from 'zod/v4';

export const authControllerLogin201Schema = z.any();

export const authControllerLoginMutationRequestSchema = loginDtoSchema;

export const authControllerLoginMutationResponseSchema =
  authControllerLogin201Schema;
