/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { authResponseDtoSchema } from './authResponseDtoSchema.ts';
import { refreshDtoSchema } from './refreshDtoSchema.ts';

export const authControllerRefresh201Schema = authResponseDtoSchema;

export const authControllerRefreshMutationRequestSchema = refreshDtoSchema;

export const authControllerRefreshMutationResponseSchema =
  authControllerRefresh201Schema;
