/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const authResponseDtoSchema = z.object({
  accessToken: z.email(),
  refreshToken: z.string(),
});
