/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { refreshDtoSchema } from './refreshDtoSchema.ts';
import { z } from 'zod/v4';

export const authControllerRefresh201Schema = z.any();

export const authControllerRefreshMutationRequestSchema = refreshDtoSchema;

export const authControllerRefreshMutationResponseSchema =
  authControllerRefresh201Schema;
