/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { logoutDtoSchema } from './logoutDtoSchema';
import { z } from 'zod/v4';

export const authControllerLogout204Schema = z.any();

export const authControllerLogoutMutationRequestSchema = logoutDtoSchema;

export const authControllerLogoutMutationResponseSchema =
  authControllerLogout204Schema;
