/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { authResponseDtoSchema } from './authResponseDtoSchema.ts';
import { loginDtoSchema } from './loginDtoSchema.ts';

export const authControllerLogin201Schema = authResponseDtoSchema;

export const authControllerLoginMutationRequestSchema = loginDtoSchema;

export const authControllerLoginMutationResponseSchema =
  authControllerLogin201Schema;
