/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const createLookupDtoSchema = z.object({
  grupo: z.string(),
  id: z.optional(z.string()),
  nome: z.string(),
});
