/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const createProjetoDtoSchema = z.object({
  empresa_id: z.optional(z.string()),
  nome: z.string().min(1).max(100),
  inicio: z.string(),
  fim: z.string(),
});
