/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const createDiariaDtoSchema = z.object({
  projetoId: z.string(),
  funcionarioId: z.string(),
  dia: z.string(),
  tipoDiariaId: z.string().nullish(),
});
