/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createDiariaDtoSchema } from './createDiariaDtoSchema.ts';
import { z } from 'zod/v4';

export const createManyDiariasDtoSchema = z.object({
  get items() {
    return z.array(createDiariaDtoSchema);
  },
});
