/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const diariaDtoSchema = z.object({
  id: z.string(),
  dia: z.string(),
  funcionarioId: z.string(),
  projetoId: z.string(),
  tipoDiariaId: z.string(),
  observacoes: z.string(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
