/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createDiariaDtoSchema } from './createDiariaDtoSchema.ts';
import { diariaEntitySchema } from './diariaEntitySchema.ts';
import { z } from 'zod/v4';

export const diariasControllerUpdatePathParamsSchema = z.object({
  id: z.string(),
});

export const diariasControllerUpdate200Schema = diariaEntitySchema;

export const diariasControllerUpdateMutationRequestSchema =
  createDiariaDtoSchema;

export const diariasControllerUpdateMutationResponseSchema =
  diariasControllerUpdate200Schema;
