/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { updateDiariaDtoSchema } from './updateDiariaDtoSchema.ts';
import { z } from 'zod/v4';

export const diariasControllerUpdateDiaria200Schema = z.any();

export const diariasControllerUpdateDiariaMutationRequestSchema =
  updateDiariaDtoSchema;

export const diariasControllerUpdateDiariaMutationResponseSchema =
  diariasControllerUpdateDiaria200Schema;
