/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createDiariaDtoSchema } from './createDiariaDtoSchema';
import { diariaDtoSchema } from './diariaDtoSchema';

export const diariasControllerCreate201Schema = diariaDtoSchema;

export const diariasControllerCreateMutationRequestSchema =
  createDiariaDtoSchema;

export const diariasControllerCreateMutationResponseSchema =
  diariasControllerCreate201Schema;
