/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createDiariaDtoSchema } from './createDiariaDtoSchema.ts';
import { diariaEntitySchema } from './diariaEntitySchema.ts';

export const diariasControllerCreate201Schema = diariaEntitySchema;

export const diariasControllerCreateMutationRequestSchema =
  createDiariaDtoSchema;

export const diariasControllerCreateMutationResponseSchema =
  diariasControllerCreate201Schema;
