/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { diariaDtoSchema } from './diariaDtoSchema';
import { z } from 'zod/v4';

export const diariasControllerFindInRangeQueryParamsSchema = z.object({
  from: z.string(),
  to: z.string(),
});

export const diariasControllerFindInRange200Schema = z.array(diariaDtoSchema);

export const diariasControllerFindInRangeQueryResponseSchema =
  diariasControllerFindInRange200Schema;
