/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createManyDiariasDtoSchema } from './createManyDiariasDtoSchema';
import { diariaDtoSchema } from './diariaDtoSchema';
import { z } from 'zod/v4';

export const diariasControllerCreateMany201Schema = z.array(diariaDtoSchema);

export const diariasControllerCreateManyMutationRequestSchema =
  createManyDiariasDtoSchema;

export const diariasControllerCreateManyMutationResponseSchema =
  diariasControllerCreateMany201Schema;
