/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { updateEmpresaDtoSchema } from './updateEmpresaDtoSchema';
import { z } from 'zod/v4';

export const empresasControllerUpdatePathParamsSchema = z.object({
  id: z.string(),
});

export const empresasControllerUpdate200Schema = z.object({});

export const empresasControllerUpdateMutationRequestSchema =
  updateEmpresaDtoSchema;

export const empresasControllerUpdateMutationResponseSchema =
  empresasControllerUpdate200Schema;
