/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { empresaDtoSchema } from './empresaDtoSchema.ts';
import { z } from 'zod/v4';

export const empresasControllerFindAll200Schema = z.array(empresaDtoSchema);

export const empresasControllerFindAllQueryResponseSchema =
  empresasControllerFindAll200Schema;
