/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getEmpresaResponseDtoSchema } from './getEmpresaResponseDtoSchema';
import { z } from 'zod/v4';

export const empresasControllerFindOnePathParamsSchema = z.object({
  id: z.string(),
});

export const empresasControllerFindOne200Schema = getEmpresaResponseDtoSchema;

export const empresasControllerFindOneQueryResponseSchema =
  empresasControllerFindOne200Schema;
