/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const empresasControllerRemovePathParamsSchema = z.object({
  id: z.string(),
});

export const empresasControllerRemove200Schema = z.any();

export const empresasControllerRemoveMutationResponseSchema =
  empresasControllerRemove200Schema;
