/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createEmpresaDtoSchema } from './createEmpresaDtoSchema';
import { z } from 'zod/v4';

export const empresasControllerCreate201Schema = z.object({});

export const empresasControllerCreateMutationRequestSchema =
  createEmpresaDtoSchema;

export const empresasControllerCreateMutationResponseSchema =
  empresasControllerCreate201Schema;
