/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const empresaDtoSchema = z.object({
  id: z.string(),
  razao: z.string(),
  fantasia: z.string(),
  cnpj: z.string(),
  registro: z.string(),
  phone: z.string(),
  email: z.string(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
