/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createFuncionarioDtoSchema } from './createFuncionarioDtoSchema';
import { z } from 'zod/v4';

export const funcionariosControllerCreate201Schema = z.object({});

export const funcionariosControllerCreateMutationRequestSchema =
  createFuncionarioDtoSchema;

export const funcionariosControllerCreateMutationResponseSchema =
  funcionariosControllerCreate201Schema;
