/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const funcionariosControllerFindOnePathParamsSchema = z.object({
  id: z.string(),
});

export const funcionariosControllerFindOne200Schema = z.any();

export const funcionariosControllerFindOneQueryResponseSchema =
  funcionariosControllerFindOne200Schema;
