/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { updateFuncionarioDtoSchema } from './updateFuncionarioDtoSchema.ts';
import { z } from 'zod/v4';

export const funcionariosControllerUpdatePathParamsSchema = z.object({
  id: z.string(),
});

export const funcionariosControllerUpdate200Schema = z.any();

export const funcionariosControllerUpdateMutationRequestSchema =
  updateFuncionarioDtoSchema;

export const funcionariosControllerUpdateMutationResponseSchema =
  funcionariosControllerUpdate200Schema;
