/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getFuncionarioResponseDtoSchema } from './getFuncionarioResponseDtoSchema';
import { z } from 'zod/v4';

export const funcionariosControllerFindOnePathParamsSchema = z.object({
  id: z.string(),
});

export const funcionariosControllerFindOne200Schema =
  getFuncionarioResponseDtoSchema;

export const funcionariosControllerFindOneQueryResponseSchema =
  funcionariosControllerFindOne200Schema;
