/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const funcionariosControllerRemovePathParamsSchema = z.object({
  id: z.string(),
});

export const funcionariosControllerRemove200Schema = z.any();

export const funcionariosControllerRemoveMutationResponseSchema =
  funcionariosControllerRemove200Schema;
