/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { empresaDtoSchema } from './empresaDtoSchema.ts';
import { z } from 'zod/v4';

export const getEmpresaResponseDtoSchema = z.object({
  get empresa() {
    return empresaDtoSchema;
  },
});
