/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { lookupDtoSchema } from './lookupDtoSchema.ts';
import { z } from 'zod/v4';

export const lookupsControllerFindAll200Schema = z.array(lookupDtoSchema);

export const lookupsControllerFindAllQueryResponseSchema =
  lookupsControllerFindAll200Schema;
