/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { updateLookupDtoSchema } from './updateLookupDtoSchema.ts';
import { z } from 'zod/v4';

export const lookupsControllerUpdatePathParamsSchema = z.object({
  grupo: z.string(),
  id: z.string(),
});

export const lookupsControllerUpdate200Schema = z.any();

export const lookupsControllerUpdateMutationRequestSchema =
  updateLookupDtoSchema;

export const lookupsControllerUpdateMutationResponseSchema =
  lookupsControllerUpdate200Schema;
