/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const lookupDtoSchema = z.object({
  grupo: z.string(),
  id: z.string(),
  nome: z.string(),
  createdAt: z.optional(z.string().datetime()),
  updatedAt: z.optional(z.string().datetime()),
});
