/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { lookupDtoSchema } from './lookupDtoSchema.ts';
import { z } from 'zod/v4';

export const lookupsControllerFindByGroupPathParamsSchema = z.object({
  grupo: z.string(),
});

export const lookupsControllerFindByGroup200Schema = z.array(lookupDtoSchema);

export const lookupsControllerFindByGroupQueryResponseSchema =
  lookupsControllerFindByGroup200Schema;
