/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const lookupsControllerFindOnePathParamsSchema = z.object({
  grupo: z.string(),
  key: z.coerce.number(),
});

export const lookupsControllerFindOne200Schema = z.any();

export const lookupsControllerFindOneQueryResponseSchema =
  lookupsControllerFindOne200Schema;
