/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const lookupsControllerRemovePathParamsSchema = z.object({
  grupo: z.string(),
  id: z.string(),
});

export const lookupsControllerRemove200Schema = z.any();

export const lookupsControllerRemoveMutationResponseSchema =
  lookupsControllerRemove200Schema;
