/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createLookupDtoSchema } from './createLookupDtoSchema';
import { z } from 'zod/v4';

export const lookupsControllerCreate201Schema = z.any();

export const lookupsControllerCreateMutationRequestSchema =
  createLookupDtoSchema;

export const lookupsControllerCreateMutationResponseSchema =
  lookupsControllerCreate201Schema;
