/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const projetosControllerFindOnePathParamsSchema = z.object({
  id: z.string(),
});

export const projetosControllerFindOne200Schema = z.any();

export const projetosControllerFindOneQueryResponseSchema =
  projetosControllerFindOne200Schema;
