/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const projetosControllerFindAll200Schema = z.array(z.object({}));

export const projetosControllerFindAllQueryResponseSchema =
  projetosControllerFindAll200Schema;
