/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { updateProjetoDtoSchema } from './updateProjetoDtoSchema.ts';
import { z } from 'zod/v4';

export const projetosControllerUpdatePathParamsSchema = z.object({
  id: z.string(),
});

export const projetosControllerUpdate200Schema = z.object({});

export const projetosControllerUpdateMutationRequestSchema =
  updateProjetoDtoSchema;

export const projetosControllerUpdateMutationResponseSchema =
  projetosControllerUpdate200Schema;
