/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { projetoDtoSchema } from './projetoDtoSchema';
import { z } from 'zod/v4';

export const projetosControllerFindAll200Schema = z.array(projetoDtoSchema);

export const projetosControllerFindAllQueryResponseSchema =
  projetosControllerFindAll200Schema;
