/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createProjetoDtoSchema } from './createProjetoDtoSchema';
import { z } from 'zod/v4';

export const projetosControllerCreate201Schema = z.object({});

export const projetosControllerCreateMutationRequestSchema =
  createProjetoDtoSchema;

export const projetosControllerCreateMutationResponseSchema =
  projetosControllerCreate201Schema;
