/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const projetosControllerRemovePathParamsSchema = z.object({
  id: z.string(),
});

export const projetosControllerRemove200Schema = z.any();

export const projetosControllerRemoveMutationResponseSchema =
  projetosControllerRemove200Schema;
