/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const projetoDtoSchema = z.object({
  id: z.string(),
  empresa_id: z.string(),
  nome: z.string(),
  inicio: z.string(),
  fim: z.string(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
