/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const updateDiariaDtoSchema = z.object({
  funcionarioId: z.string(),
  projetoId: z.string(),
  dia: z.string(),
  tipo: z.object({}),
});
