/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const updateEmpresaDtoSchema = z.object({
  razao: z.optional(z.string().min(1).max(100)),
  fantasia: z.optional(z.string().min(0).max(100)),
  cnpj: z.optional(z.string().min(1).max(15)),
  registro: z.optional(z.string()),
  phone: z.optional(z.string().min(0).max(20)),
  email: z.optional(z.email()),
});
