/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const updateProjetoDtoSchema = z.object({
  empresaId: z.optional(z.string()),
  nome: z.optional(z.string().min(1).max(100)),
  inicio: z.optional(z.string()),
  fim: z.optional(z.string()),
});
