/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { funcionarioBeneficioDtoSchema } from './funcionarioBeneficioDtoSchema';
import { z } from 'zod/v4';

export const updateFuncionarioDtoSchema = z.object({
  nome: z.optional(z.string().min(1).max(100)),
  social: z.optional(z.string().min(0).max(100)),
  cpf: z.optional(z.string().min(1).max(15)),
  nascimento: z.optional(z.string()),
  phone: z.optional(z.string().min(0).max(20)),
  email: z.optional(z.email()),
  projetoId: z.optional(z.string()),
  rg: z.optional(z.string().min(0).max(11)),
  funcao: z.optional(z.string().min(0).max(30)),
  dependetes: z.optional(z.number()),
  get beneficios() {
    return z.optional(z.array(funcionarioBeneficioDtoSchema));
  },
});
