/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4';

export const updateLookupDtoSchema = z.object({
  grupo: z.optional(z.string()),
  nome: z.optional(z.string()),
});
