/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  ProjetosControllerUpdateMutationRequest,
  ProjetosControllerUpdateMutationResponse,
  ProjetosControllerUpdatePathParams,
} from '../../types/ProjetosControllerUpdate.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const projetosControllerUpdateMutationKey = () =>
  [{ url: '/projetos/:id' }] as const;

export type ProjetosControllerUpdateMutationKey = ReturnType<
  typeof projetosControllerUpdateMutationKey
>;

/**
 * {@link /projetos/:id}
 */
export async function projetosControllerUpdate(
  id: ProjetosControllerUpdatePathParams['id'],
  data?: ProjetosControllerUpdateMutationRequest,
  config: Partial<RequestConfig<ProjetosControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ProjetosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    ProjetosControllerUpdateMutationRequest
  >({
    method: 'PATCH',
    url: `/projetos/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function projetosControllerUpdateMutationOptions(
  config: Partial<RequestConfig<ProjetosControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = projetosControllerUpdateMutationKey();
  return mutationOptions<
    ProjetosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: ProjetosControllerUpdatePathParams['id'];
      data?: ProjetosControllerUpdateMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return projetosControllerUpdate(id, data, config);
    },
  });
}

/**
 * {@link /projetos/:id}
 */
export function useProjetosControllerUpdate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ProjetosControllerUpdateMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: ProjetosControllerUpdatePathParams['id'];
        data?: ProjetosControllerUpdateMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<ProjetosControllerUpdateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? projetosControllerUpdateMutationKey();

  const baseOptions = projetosControllerUpdateMutationOptions(
    config
  ) as UseMutationOptions<
    ProjetosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: ProjetosControllerUpdatePathParams['id'];
      data?: ProjetosControllerUpdateMutationRequest;
    },
    TContext
  >;

  return useMutation<
    ProjetosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: ProjetosControllerUpdatePathParams['id'];
      data?: ProjetosControllerUpdateMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    ProjetosControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: ProjetosControllerUpdatePathParams['id'];
      data?: ProjetosControllerUpdateMutationRequest;
    },
    TContext
  >;
}
