/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  ProjetosControllerCreateMutationRequest,
  ProjetosControllerCreateMutationResponse,
} from '../../types/ProjetosControllerCreate.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const projetosControllerCreateMutationKey = () =>
  [{ url: '/projetos' }] as const;

export type ProjetosControllerCreateMutationKey = ReturnType<
  typeof projetosControllerCreateMutationKey
>;

/**
 * {@link /projetos}
 */
export async function projetosControllerCreate(
  data: ProjetosControllerCreateMutationRequest,
  config: Partial<RequestConfig<ProjetosControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ProjetosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    ProjetosControllerCreateMutationRequest
  >({ method: 'POST', url: `/projetos`, data: requestData, ...requestConfig });
  return res.data;
}

export function projetosControllerCreateMutationOptions(
  config: Partial<RequestConfig<ProjetosControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = projetosControllerCreateMutationKey();
  return mutationOptions<
    ProjetosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: ProjetosControllerCreateMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return projetosControllerCreate(data, config);
    },
  });
}

/**
 * {@link /projetos}
 */
export function useProjetosControllerCreate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ProjetosControllerCreateMutationResponse,
      ResponseErrorConfig<Error>,
      { data: ProjetosControllerCreateMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<ProjetosControllerCreateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? projetosControllerCreateMutationKey();

  const baseOptions = projetosControllerCreateMutationOptions(
    config
  ) as UseMutationOptions<
    ProjetosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: ProjetosControllerCreateMutationRequest },
    TContext
  >;

  return useMutation<
    ProjetosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: ProjetosControllerCreateMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    ProjetosControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: ProjetosControllerCreateMutationRequest },
    TContext
  >;
}
