/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  ProjetosControllerFindOneQueryResponse,
  ProjetosControllerFindOnePathParams,
} from '../../types/ProjetosControllerFindOne';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const projetosControllerFindOneQueryKey = (
  id: ProjetosControllerFindOnePathParams['id']
) => [{ url: '/projetos/:id', params: { id: id } }] as const;

export type ProjetosControllerFindOneQueryKey = ReturnType<
  typeof projetosControllerFindOneQueryKey
>;

/**
 * {@link /projetos/:id}
 */
export async function projetosControllerFindOne(
  id: ProjetosControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ProjetosControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/projetos/${id}`, ...requestConfig });
  return res.data;
}

export function projetosControllerFindOneQueryOptions(
  id: ProjetosControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = projetosControllerFindOneQueryKey(id);
  return queryOptions<
    ProjetosControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    ProjetosControllerFindOneQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return projetosControllerFindOne(id, config);
    },
  });
}

/**
 * {@link /projetos/:id}
 */
export function useProjetosControllerFindOne<
  TData = ProjetosControllerFindOneQueryResponse,
  TQueryData = ProjetosControllerFindOneQueryResponse,
  TQueryKey extends QueryKey = ProjetosControllerFindOneQueryKey
>(
  id: ProjetosControllerFindOnePathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        ProjetosControllerFindOneQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? projetosControllerFindOneQueryKey(id);

  const query = useQuery(
    {
      ...projetosControllerFindOneQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
