/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  ProjetosControllerRemoveMutationResponse,
  ProjetosControllerRemovePathParams,
} from '../../types/ProjetosControllerRemove.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const projetosControllerRemoveMutationKey = () =>
  [{ url: '/projetos/:id' }] as const;

export type ProjetosControllerRemoveMutationKey = ReturnType<
  typeof projetosControllerRemoveMutationKey
>;

/**
 * {@link /projetos/:id}
 */
export async function projetosControllerRemove(
  id: ProjetosControllerRemovePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ProjetosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'DELETE', url: `/projetos/${id}`, ...requestConfig });
  return res.data;
}

export function projetosControllerRemoveMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const mutationKey = projetosControllerRemoveMutationKey();
  return mutationOptions<
    ProjetosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ProjetosControllerRemovePathParams['id'] },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return projetosControllerRemove(id, config);
    },
  });
}

/**
 * {@link /projetos/:id}
 */
export function useProjetosControllerRemove<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ProjetosControllerRemoveMutationResponse,
      ResponseErrorConfig<Error>,
      { id: ProjetosControllerRemovePathParams['id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? projetosControllerRemoveMutationKey();

  const baseOptions = projetosControllerRemoveMutationOptions(
    config
  ) as UseMutationOptions<
    ProjetosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ProjetosControllerRemovePathParams['id'] },
    TContext
  >;

  return useMutation<
    ProjetosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ProjetosControllerRemovePathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    ProjetosControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    { id: ProjetosControllerRemovePathParams['id'] },
    TContext
  >;
}
