/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type { ProjetosControllerFindAllQueryResponse } from '../../types/ProjetosControllerFindAll';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const projetosControllerFindAllQueryKey = () =>
  [{ url: '/projetos' }] as const;

export type ProjetosControllerFindAllQueryKey = ReturnType<
  typeof projetosControllerFindAllQueryKey
>;

/**
 * {@link /projetos}
 */
export async function projetosControllerFindAll(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ProjetosControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/projetos`, ...requestConfig });
  return res.data;
}

export function projetosControllerFindAllQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = projetosControllerFindAllQueryKey();
  return queryOptions<
    ProjetosControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    ProjetosControllerFindAllQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return projetosControllerFindAll(config);
    },
  });
}

/**
 * {@link /projetos}
 */
export function useProjetosControllerFindAll<
  TData = ProjetosControllerFindAllQueryResponse,
  TQueryData = ProjetosControllerFindAllQueryResponse,
  TQueryKey extends QueryKey = ProjetosControllerFindAllQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ProjetosControllerFindAllQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? projetosControllerFindAllQueryKey();

  const query = useQuery(
    {
      ...projetosControllerFindAllQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
