/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  DiariasControllerUpdateDiariaMutationRequest,
  DiariasControllerUpdateDiariaMutationResponse,
} from '../../types/DiariasControllerUpdateDiaria.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const diariasControllerUpdateDiariaMutationKey = () =>
  [{ url: '/diarias' }] as const;

export type DiariasControllerUpdateDiariaMutationKey = ReturnType<
  typeof diariasControllerUpdateDiariaMutationKey
>;

/**
 * {@link /diarias}
 */
export async function diariasControllerUpdateDiaria(
  data: DiariasControllerUpdateDiariaMutationRequest,
  config: Partial<
    RequestConfig<DiariasControllerUpdateDiariaMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    DiariasControllerUpdateDiariaMutationResponse,
    ResponseErrorConfig<Error>,
    DiariasControllerUpdateDiariaMutationRequest
  >({ method: 'PATCH', url: `/diarias`, data: requestData, ...requestConfig });
  return res.data;
}

export function diariasControllerUpdateDiariaMutationOptions(
  config: Partial<
    RequestConfig<DiariasControllerUpdateDiariaMutationRequest>
  > & { client?: typeof fetch } = {}
) {
  const mutationKey = diariasControllerUpdateDiariaMutationKey();
  return mutationOptions<
    DiariasControllerUpdateDiariaMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerUpdateDiariaMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return diariasControllerUpdateDiaria(data, config);
    },
  });
}

/**
 * {@link /diarias}
 */
export function useDiariasControllerUpdateDiaria<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DiariasControllerUpdateDiariaMutationResponse,
      ResponseErrorConfig<Error>,
      { data: DiariasControllerUpdateDiariaMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<DiariasControllerUpdateDiariaMutationRequest>
    > & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? diariasControllerUpdateDiariaMutationKey();

  const baseOptions = diariasControllerUpdateDiariaMutationOptions(
    config
  ) as UseMutationOptions<
    DiariasControllerUpdateDiariaMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerUpdateDiariaMutationRequest },
    TContext
  >;

  return useMutation<
    DiariasControllerUpdateDiariaMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerUpdateDiariaMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DiariasControllerUpdateDiariaMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerUpdateDiariaMutationRequest },
    TContext
  >;
}
