/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  DiariasControllerFindInRangeQueryResponse,
  DiariasControllerFindInRangeQueryParams,
} from '../../types/DiariasControllerFindInRange.ts';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const diariasControllerFindInRangeQueryKey = (
  params: DiariasControllerFindInRangeQueryParams
) => [{ url: '/diarias' }, ...(params ? [params] : [])] as const;

export type DiariasControllerFindInRangeQueryKey = ReturnType<
  typeof diariasControllerFindInRangeQueryKey
>;

/**
 * {@link /diarias}
 */
export async function diariasControllerFindInRange(
  params: DiariasControllerFindInRangeQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DiariasControllerFindInRangeQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/diarias`, params, ...requestConfig });
  return res.data;
}

export function diariasControllerFindInRangeQueryOptions(
  params: DiariasControllerFindInRangeQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = diariasControllerFindInRangeQueryKey(params);
  return queryOptions<
    DiariasControllerFindInRangeQueryResponse,
    ResponseErrorConfig<Error>,
    DiariasControllerFindInRangeQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return diariasControllerFindInRange(params, config);
    },
  });
}

/**
 * {@link /diarias}
 */
export function useDiariasControllerFindInRange<
  TData = DiariasControllerFindInRangeQueryResponse,
  TQueryData = DiariasControllerFindInRangeQueryResponse,
  TQueryKey extends QueryKey = DiariasControllerFindInRangeQueryKey
>(
  params: DiariasControllerFindInRangeQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        DiariasControllerFindInRangeQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? diariasControllerFindInRangeQueryKey(params);

  const query = useQuery(
    {
      ...diariasControllerFindInRangeQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
