/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  DiariasControllerCreateMutationRequest,
  DiariasControllerCreateMutationResponse,
} from '../../types/DiariasControllerCreate.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const diariasControllerCreateMutationKey = () =>
  [{ url: '/diarias' }] as const;

export type DiariasControllerCreateMutationKey = ReturnType<
  typeof diariasControllerCreateMutationKey
>;

/**
 * {@link /diarias}
 */
export async function diariasControllerCreate(
  data: DiariasControllerCreateMutationRequest,
  config: Partial<RequestConfig<DiariasControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    DiariasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    DiariasControllerCreateMutationRequest
  >({ method: 'POST', url: `/diarias`, data: requestData, ...requestConfig });
  return res.data;
}

export function diariasControllerCreateMutationOptions(
  config: Partial<RequestConfig<DiariasControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = diariasControllerCreateMutationKey();
  return mutationOptions<
    DiariasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return diariasControllerCreate(data, config);
    },
  });
}

/**
 * {@link /diarias}
 */
export function useDiariasControllerCreate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DiariasControllerCreateMutationResponse,
      ResponseErrorConfig<Error>,
      { data: DiariasControllerCreateMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<DiariasControllerCreateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? diariasControllerCreateMutationKey();

  const baseOptions = diariasControllerCreateMutationOptions(
    config
  ) as UseMutationOptions<
    DiariasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateMutationRequest },
    TContext
  >;

  return useMutation<
    DiariasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DiariasControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateMutationRequest },
    TContext
  >;
}
