/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  DiariasControllerUpdateMutationRequest,
  DiariasControllerUpdateMutationResponse,
  DiariasControllerUpdatePathParams,
} from '../../types/DiariasControllerUpdate';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const diariasControllerUpdateMutationKey = () =>
  [{ url: '/diarias/:id' }] as const;

export type DiariasControllerUpdateMutationKey = ReturnType<
  typeof diariasControllerUpdateMutationKey
>;

/**
 * {@link /diarias/:id}
 */
export async function diariasControllerUpdate(
  id: DiariasControllerUpdatePathParams['id'],
  data: DiariasControllerUpdateMutationRequest,
  config: Partial<RequestConfig<DiariasControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    DiariasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    DiariasControllerUpdateMutationRequest
  >({
    method: 'PATCH',
    url: `/diarias/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function diariasControllerUpdateMutationOptions(
  config: Partial<RequestConfig<DiariasControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = diariasControllerUpdateMutationKey();
  return mutationOptions<
    DiariasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DiariasControllerUpdatePathParams['id'];
      data: DiariasControllerUpdateMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return diariasControllerUpdate(id, data, config);
    },
  });
}

/**
 * {@link /diarias/:id}
 */
export function useDiariasControllerUpdate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DiariasControllerUpdateMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: DiariasControllerUpdatePathParams['id'];
        data: DiariasControllerUpdateMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<DiariasControllerUpdateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? diariasControllerUpdateMutationKey();

  const baseOptions = diariasControllerUpdateMutationOptions(
    config
  ) as UseMutationOptions<
    DiariasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DiariasControllerUpdatePathParams['id'];
      data: DiariasControllerUpdateMutationRequest;
    },
    TContext
  >;

  return useMutation<
    DiariasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DiariasControllerUpdatePathParams['id'];
      data: DiariasControllerUpdateMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DiariasControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DiariasControllerUpdatePathParams['id'];
      data: DiariasControllerUpdateMutationRequest;
    },
    TContext
  >;
}
