/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  DiariasControllerCreateManyMutationRequest,
  DiariasControllerCreateManyMutationResponse,
} from '../../types/DiariasControllerCreateMany';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const diariasControllerCreateManyMutationKey = () =>
  [{ url: '/diarias/bulk' }] as const;

export type DiariasControllerCreateManyMutationKey = ReturnType<
  typeof diariasControllerCreateManyMutationKey
>;

/**
 * {@link /diarias/bulk}
 */
export async function diariasControllerCreateMany(
  data: DiariasControllerCreateManyMutationRequest,
  config: Partial<RequestConfig<DiariasControllerCreateManyMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    DiariasControllerCreateManyMutationResponse,
    ResponseErrorConfig<Error>,
    DiariasControllerCreateManyMutationRequest
  >({
    method: 'POST',
    url: `/diarias/bulk`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function diariasControllerCreateManyMutationOptions(
  config: Partial<RequestConfig<DiariasControllerCreateManyMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = diariasControllerCreateManyMutationKey();
  return mutationOptions<
    DiariasControllerCreateManyMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateManyMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return diariasControllerCreateMany(data, config);
    },
  });
}

/**
 * {@link /diarias/bulk}
 */
export function useDiariasControllerCreateMany<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DiariasControllerCreateManyMutationResponse,
      ResponseErrorConfig<Error>,
      { data: DiariasControllerCreateManyMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<DiariasControllerCreateManyMutationRequest>
    > & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? diariasControllerCreateManyMutationKey();

  const baseOptions = diariasControllerCreateManyMutationOptions(
    config
  ) as UseMutationOptions<
    DiariasControllerCreateManyMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateManyMutationRequest },
    TContext
  >;

  return useMutation<
    DiariasControllerCreateManyMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateManyMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DiariasControllerCreateManyMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DiariasControllerCreateManyMutationRequest },
    TContext
  >;
}
