/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  LookupsControllerFindOneQueryResponse,
  LookupsControllerFindOnePathParams,
} from '../../types/LookupsControllerFindOne';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const lookupsControllerFindOneQueryKey = (
  grupo: LookupsControllerFindOnePathParams['grupo'],
  id: LookupsControllerFindOnePathParams['id']
) =>
  [{ url: '/lookups/:grupo/:id', params: { grupo: grupo, id: id } }] as const;

export type LookupsControllerFindOneQueryKey = ReturnType<
  typeof lookupsControllerFindOneQueryKey
>;

/**
 * {@link /lookups/:grupo/:id}
 */
export async function lookupsControllerFindOne(
  grupo: LookupsControllerFindOnePathParams['grupo'],
  id: LookupsControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LookupsControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/lookups/${grupo}/${id}`, ...requestConfig });
  return res.data;
}

export function lookupsControllerFindOneQueryOptions(
  grupo: LookupsControllerFindOnePathParams['grupo'],
  id: LookupsControllerFindOnePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = lookupsControllerFindOneQueryKey(grupo, id);
  return queryOptions<
    LookupsControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    LookupsControllerFindOneQueryResponse,
    typeof queryKey
  >({
    enabled: !!(grupo && id),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return lookupsControllerFindOne(grupo, id, config);
    },
  });
}

/**
 * {@link /lookups/:grupo/:id}
 */
export function useLookupsControllerFindOne<
  TData = LookupsControllerFindOneQueryResponse,
  TQueryData = LookupsControllerFindOneQueryResponse,
  TQueryKey extends QueryKey = LookupsControllerFindOneQueryKey
>(
  grupo: LookupsControllerFindOnePathParams['grupo'],
  id: LookupsControllerFindOnePathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        LookupsControllerFindOneQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? lookupsControllerFindOneQueryKey(grupo, id);

  const query = useQuery(
    {
      ...lookupsControllerFindOneQueryOptions(grupo, id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
