/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  LookupsControllerFindOneQueryResponse,
  LookupsControllerFindOnePathParams,
} from '../../types/LookupsControllerFindOne.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const lookupsControllerFindOneQueryKey = (
  grupo: LookupsControllerFindOnePathParams['grupo'],
  key: LookupsControllerFindOnePathParams['key']
) =>
  [
    { url: '/lookups/:grupo/:key', params: { grupo: grupo, key: key } },
  ] as const;

export type LookupsControllerFindOneQueryKey = ReturnType<
  typeof lookupsControllerFindOneQueryKey
>;

/**
 * {@link /lookups/:grupo/:key}
 */
export async function lookupsControllerFindOne(
  grupo: LookupsControllerFindOnePathParams['grupo'],
  key: LookupsControllerFindOnePathParams['key'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LookupsControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/lookups/${grupo}/${key}`, ...requestConfig });
  return res.data;
}

export function lookupsControllerFindOneQueryOptions(
  grupo: LookupsControllerFindOnePathParams['grupo'],
  key: LookupsControllerFindOnePathParams['key'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = lookupsControllerFindOneQueryKey(grupo, key);
  return queryOptions<
    LookupsControllerFindOneQueryResponse,
    ResponseErrorConfig<Error>,
    LookupsControllerFindOneQueryResponse,
    typeof queryKey
  >({
    enabled: !!(grupo && key),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return lookupsControllerFindOne(grupo, key, config);
    },
  });
}

/**
 * {@link /lookups/:grupo/:key}
 */
export function useLookupsControllerFindOne<
  TData = LookupsControllerFindOneQueryResponse,
  TQueryData = LookupsControllerFindOneQueryResponse,
  TQueryKey extends QueryKey = LookupsControllerFindOneQueryKey
>(
  grupo: LookupsControllerFindOnePathParams['grupo'],
  key: LookupsControllerFindOnePathParams['key'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        LookupsControllerFindOneQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? lookupsControllerFindOneQueryKey(grupo, key);

  const query = useQuery(
    {
      ...lookupsControllerFindOneQueryOptions(grupo, key, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
