/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  LookupsControllerFindByGroupQueryResponse,
  LookupsControllerFindByGroupPathParams,
} from '../../types/LookupsControllerFindByGroup';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const lookupsControllerFindByGroupQueryKey = (
  grupo: LookupsControllerFindByGroupPathParams['grupo']
) => [{ url: '/lookups/:grupo', params: { grupo: grupo } }] as const;

export type LookupsControllerFindByGroupQueryKey = ReturnType<
  typeof lookupsControllerFindByGroupQueryKey
>;

/**
 * {@link /lookups/:grupo}
 */
export async function lookupsControllerFindByGroup(
  grupo: LookupsControllerFindByGroupPathParams['grupo'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LookupsControllerFindByGroupQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/lookups/${grupo}`, ...requestConfig });
  return res.data;
}

export function lookupsControllerFindByGroupQueryOptions(
  grupo: LookupsControllerFindByGroupPathParams['grupo'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = lookupsControllerFindByGroupQueryKey(grupo);
  return queryOptions<
    LookupsControllerFindByGroupQueryResponse,
    ResponseErrorConfig<Error>,
    LookupsControllerFindByGroupQueryResponse,
    typeof queryKey
  >({
    enabled: !!grupo,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return lookupsControllerFindByGroup(grupo, config);
    },
  });
}

/**
 * {@link /lookups/:grupo}
 */
export function useLookupsControllerFindByGroup<
  TData = LookupsControllerFindByGroupQueryResponse,
  TQueryData = LookupsControllerFindByGroupQueryResponse,
  TQueryKey extends QueryKey = LookupsControllerFindByGroupQueryKey
>(
  grupo: LookupsControllerFindByGroupPathParams['grupo'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        LookupsControllerFindByGroupQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? lookupsControllerFindByGroupQueryKey(grupo);

  const query = useQuery(
    {
      ...lookupsControllerFindByGroupQueryOptions(grupo, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
