/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type { LookupsControllerFindAllQueryResponse } from '../../types/LookupsControllerFindAll.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';

export const lookupsControllerFindAllQueryKey = () =>
  [{ url: '/lookups' }] as const;

export type LookupsControllerFindAllQueryKey = ReturnType<
  typeof lookupsControllerFindAllQueryKey
>;

/**
 * {@link /lookups}
 */
export async function lookupsControllerFindAll(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LookupsControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/lookups`, ...requestConfig });
  return res.data;
}

export function lookupsControllerFindAllQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = lookupsControllerFindAllQueryKey();
  return queryOptions<
    LookupsControllerFindAllQueryResponse,
    ResponseErrorConfig<Error>,
    LookupsControllerFindAllQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return lookupsControllerFindAll(config);
    },
  });
}

/**
 * {@link /lookups}
 */
export function useLookupsControllerFindAll<
  TData = LookupsControllerFindAllQueryResponse,
  TQueryData = LookupsControllerFindAllQueryResponse,
  TQueryKey extends QueryKey = LookupsControllerFindAllQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        LookupsControllerFindAllQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? lookupsControllerFindAllQueryKey();

  const query = useQuery(
    {
      ...lookupsControllerFindAllQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
