/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  LookupsControllerCreateMutationRequest,
  LookupsControllerCreateMutationResponse,
} from '../../types/LookupsControllerCreate';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const lookupsControllerCreateMutationKey = () =>
  [{ url: '/lookups' }] as const;

export type LookupsControllerCreateMutationKey = ReturnType<
  typeof lookupsControllerCreateMutationKey
>;

/**
 * {@link /lookups}
 */
export async function lookupsControllerCreate(
  data: LookupsControllerCreateMutationRequest,
  config: Partial<RequestConfig<LookupsControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    LookupsControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    LookupsControllerCreateMutationRequest
  >({ method: 'POST', url: `/lookups`, data: requestData, ...requestConfig });
  return res.data;
}

export function lookupsControllerCreateMutationOptions(
  config: Partial<RequestConfig<LookupsControllerCreateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = lookupsControllerCreateMutationKey();
  return mutationOptions<
    LookupsControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: LookupsControllerCreateMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return lookupsControllerCreate(data, config);
    },
  });
}

/**
 * {@link /lookups}
 */
export function useLookupsControllerCreate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      LookupsControllerCreateMutationResponse,
      ResponseErrorConfig<Error>,
      { data: LookupsControllerCreateMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<LookupsControllerCreateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? lookupsControllerCreateMutationKey();

  const baseOptions = lookupsControllerCreateMutationOptions(
    config
  ) as UseMutationOptions<
    LookupsControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: LookupsControllerCreateMutationRequest },
    TContext
  >;

  return useMutation<
    LookupsControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: LookupsControllerCreateMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    LookupsControllerCreateMutationResponse,
    ResponseErrorConfig<Error>,
    { data: LookupsControllerCreateMutationRequest },
    TContext
  >;
}
