/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  LookupsControllerUpdateMutationRequest,
  LookupsControllerUpdateMutationResponse,
  LookupsControllerUpdatePathParams,
} from '../../types/LookupsControllerUpdate.ts';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const lookupsControllerUpdateMutationKey = () =>
  [{ url: '/lookups/:grupo/:id' }] as const;

export type LookupsControllerUpdateMutationKey = ReturnType<
  typeof lookupsControllerUpdateMutationKey
>;

/**
 * {@link /lookups/:grupo/:id}
 */
export async function lookupsControllerUpdate(
  grupo: LookupsControllerUpdatePathParams['grupo'],
  id: LookupsControllerUpdatePathParams['id'],
  data?: LookupsControllerUpdateMutationRequest,
  config: Partial<RequestConfig<LookupsControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    LookupsControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    LookupsControllerUpdateMutationRequest
  >({
    method: 'PATCH',
    url: `/lookups/${grupo}/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function lookupsControllerUpdateMutationOptions(
  config: Partial<RequestConfig<LookupsControllerUpdateMutationRequest>> & {
    client?: typeof fetch;
  } = {}
) {
  const mutationKey = lookupsControllerUpdateMutationKey();
  return mutationOptions<
    LookupsControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerUpdatePathParams['grupo'];
      id: LookupsControllerUpdatePathParams['id'];
      data?: LookupsControllerUpdateMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ grupo, id, data }) => {
      return lookupsControllerUpdate(grupo, id, data, config);
    },
  });
}

/**
 * {@link /lookups/:grupo/:id}
 */
export function useLookupsControllerUpdate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      LookupsControllerUpdateMutationResponse,
      ResponseErrorConfig<Error>,
      {
        grupo: LookupsControllerUpdatePathParams['grupo'];
        id: LookupsControllerUpdatePathParams['id'];
        data?: LookupsControllerUpdateMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<LookupsControllerUpdateMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? lookupsControllerUpdateMutationKey();

  const baseOptions = lookupsControllerUpdateMutationOptions(
    config
  ) as UseMutationOptions<
    LookupsControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerUpdatePathParams['grupo'];
      id: LookupsControllerUpdatePathParams['id'];
      data?: LookupsControllerUpdateMutationRequest;
    },
    TContext
  >;

  return useMutation<
    LookupsControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerUpdatePathParams['grupo'];
      id: LookupsControllerUpdatePathParams['id'];
      data?: LookupsControllerUpdateMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    LookupsControllerUpdateMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerUpdatePathParams['grupo'];
      id: LookupsControllerUpdatePathParams['id'];
      data?: LookupsControllerUpdateMutationRequest;
    },
    TContext
  >;
}
