/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios';
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query';
import type {
  LookupsControllerRemoveMutationResponse,
  LookupsControllerRemovePathParams,
} from '../../types/LookupsControllerRemove';
import { mutationOptions, useMutation } from '@tanstack/react-query';

export const lookupsControllerRemoveMutationKey = () =>
  [{ url: '/lookups/:grupo/:id' }] as const;

export type LookupsControllerRemoveMutationKey = ReturnType<
  typeof lookupsControllerRemoveMutationKey
>;

/**
 * {@link /lookups/:grupo/:id}
 */
export async function lookupsControllerRemove(
  grupo: LookupsControllerRemovePathParams['grupo'],
  id: LookupsControllerRemovePathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LookupsControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'DELETE', url: `/lookups/${grupo}/${id}`, ...requestConfig });
  return res.data;
}

export function lookupsControllerRemoveMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const mutationKey = lookupsControllerRemoveMutationKey();
  return mutationOptions<
    LookupsControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerRemovePathParams['grupo'];
      id: LookupsControllerRemovePathParams['id'];
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ grupo, id }) => {
      return lookupsControllerRemove(grupo, id, config);
    },
  });
}

/**
 * {@link /lookups/:grupo/:id}
 */
export function useLookupsControllerRemove<TContext>(
  options: {
    mutation?: UseMutationOptions<
      LookupsControllerRemoveMutationResponse,
      ResponseErrorConfig<Error>,
      {
        grupo: LookupsControllerRemovePathParams['grupo'];
        id: LookupsControllerRemovePathParams['id'];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? lookupsControllerRemoveMutationKey();

  const baseOptions = lookupsControllerRemoveMutationOptions(
    config
  ) as UseMutationOptions<
    LookupsControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerRemovePathParams['grupo'];
      id: LookupsControllerRemovePathParams['id'];
    },
    TContext
  >;

  return useMutation<
    LookupsControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerRemovePathParams['grupo'];
      id: LookupsControllerRemovePathParams['id'];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    LookupsControllerRemoveMutationResponse,
    ResponseErrorConfig<Error>,
    {
      grupo: LookupsControllerRemovePathParams['grupo'];
      id: LookupsControllerRemovePathParams['id'];
    },
    TContext
  >;
}
