/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CadastroDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  nomeRazao: string;
  /**
   * @type string
   */
  socialFantasia: string;
  /**
   * @type string
   */
  cpfCnpj: string;
  /**
   * @type string
   */
  nascimentoRegistro: string;
  /**
   * @type string
   */
  phone: string;
  /**
   * @type string
   */
  email: string;
  /**
   * @type string
   */
  rg: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
};
