/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreatePessoaJuridicaDto = {
  /**
   * @type string, uuid
   */
  businessId: string;
  /**
   * @minLength 1
   * @maxLength 50
   * @type string
   */
  cnpj: string;
  /**
   * @type string
   */
  accessTokenEncrypted: string;
  /**
   * @minLength 1
   * @maxLength 255
   * @type string
   */
  webhookVerifyToken: string;
  /**
   * @minLength 0
   * @maxLength 255
   * @type string
   */
  nomeFantasia?: string | null;
};
