/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FuncionarioDto = {
  /**
   * @type string
   */
  id: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
  /**
   * @type object
   */
  projetos: object;
};
