/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetFuncionarioResponseDto } from './GetFuncionarioResponseDto.ts';

export type FuncionariosControllerFindAll200 = GetFuncionarioResponseDto[];

export type FuncionariosControllerFindAllQueryResponse =
  FuncionariosControllerFindAll200;

export type FuncionariosControllerFindAllQuery = {
  Response: FuncionariosControllerFindAll200;
  Errors: any;
};
