/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CadastroDto } from './CadastroDto.ts';
import type { FuncionarioDto } from './FuncionarioDto.ts';

export type GetFuncionarioResponseDto = {
  /**
   * @type object
   */
  funcionario: FuncionarioDto;
  /**
   * @type object
   */
  cadastro: CadastroDto;
};
