/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type HealthControllerGetHealth200 = any;

export type HealthControllerGetHealthQueryResponse =
  HealthControllerGetHealth200;

export type HealthControllerGetHealthQuery = {
  Response: HealthControllerGetHealth200;
  Errors: any;
};
