/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PessoasJuridicasControllerFindOnePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type PessoasJuridicasControllerFindOneQueryParams = {
  /**
   * @type string
   */
  businessId: string;
};

export type PessoasJuridicasControllerFindOne200 = any;

export type PessoasJuridicasControllerFindOneQueryResponse =
  PessoasJuridicasControllerFindOne200;

export type PessoasJuridicasControllerFindOneQuery = {
  Response: PessoasJuridicasControllerFindOne200;
  PathParams: PessoasJuridicasControllerFindOnePathParams;
  QueryParams: PessoasJuridicasControllerFindOneQueryParams;
  Errors: any;
};
