/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PessoasJuridicasControllerRemovePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type PessoasJuridicasControllerRemoveQueryParams = {
  /**
   * @type string
   */
  businessId: string;
};

export type PessoasJuridicasControllerRemove200 = any;

export type PessoasJuridicasControllerRemoveMutationResponse =
  PessoasJuridicasControllerRemove200;

export type PessoasJuridicasControllerRemoveMutation = {
  Response: PessoasJuridicasControllerRemove200;
  PathParams: PessoasJuridicasControllerRemovePathParams;
  QueryParams: PessoasJuridicasControllerRemoveQueryParams;
  Errors: any;
};
