/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdatePessoaJuridicaDto } from './UpdatePessoaJuridicaDto.ts';

export type PessoasJuridicasControllerUpdatePathParams = {
  /**
   * @type string
   */
  id: string;
};

export type PessoasJuridicasControllerUpdate200 = any;

export type PessoasJuridicasControllerUpdateMutationRequest =
  UpdatePessoaJuridicaDto;

export type PessoasJuridicasControllerUpdateMutationResponse =
  PessoasJuridicasControllerUpdate200;

export type PessoasJuridicasControllerUpdateMutation = {
  Response: PessoasJuridicasControllerUpdate200;
  Request: PessoasJuridicasControllerUpdateMutationRequest;
  PathParams: PessoasJuridicasControllerUpdatePathParams;
  Errors: any;
};
