/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PessoasJuridicasControllerFindAllQueryParams = {
  /**
   * @type string
   */
  businessId: string;
};

export type PessoasJuridicasControllerFindAll200 = any;

export type PessoasJuridicasControllerFindAllQueryResponse =
  PessoasJuridicasControllerFindAll200;

export type PessoasJuridicasControllerFindAllQuery = {
  Response: PessoasJuridicasControllerFindAll200;
  QueryParams: PessoasJuridicasControllerFindAllQueryParams;
  Errors: any;
};
