/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdatePessoaJuridicaDto = {
  /**
   * @type string | undefined, uuid
   */
  businessId?: string;
  /**
   * @minLength 1
   * @maxLength 50
   * @type string | undefined
   */
  cnpj?: string;
  /**
   * @type string | undefined
   */
  accessTokenEncrypted?: string;
  /**
   * @minLength 1
   * @maxLength 255
   * @type string | undefined
   */
  webhookVerifyToken?: string;
  /**
   * @minLength 0
   * @maxLength 255
   * @type string
   */
  nomeFantasia?: string | null;
};
